# Третий аудит Brig — отчёт

Проведён по [AUDIT_PROMPT-3.md](AUDIT_PROMPT-3.md) (T-154, #276).
Предыдущие: [AUDIT_REPORT.md](AUDIT_REPORT.md) (первый),
[AUDIT_REPORT-2.md](AUDIT_REPORT-2.md) (второй). Оба — исторические
документы, не правятся. План по итогам — `tasks/wave-16.md` …
`tasks/wave-19.md`, решения человека — DD T-250…T-259 в
[tasks/decisions.md](tasks/decisions.md).

ID продолжают нумерацию второго аудита, чтобы не путать: P-15+, S-13+,
G-16+, R-8+, F-9+ (F-1…F-8 — контуры второго аудита), новые слои — X-1+,
D-1+. Предложения — L-1+.

## 1. Шапка

- **Состояние:** `main` @ `77c0cea` (2026-09-30, `feat(stdlib): add
  Behavior and spawn_behavior (§13.2) [T-171] (#384)`). Всё влитое после —
  вне аудита. Доска и issues — на 2026-09-30 вечер.
- **Окружение:** go1.27.1 linux/amd64, 8 ядер, Linux 7.2.5,
  golangci-lint (из окружения), CPython 3 для сравнения скорости.
- **Что запускалось (реальные команды → итог):**
  - `make all` → 0 (1 мин 55 с): `check-examples` — `blocks: checked 83,
    failed 0, pending 3`; `run-examples` — 8 из 9 (сервер пропущен);
    `corpus: 29 files — run 4, check 2, parse 17, none 6`; `plan-check: 0
    problems`;
  - `make test-race` → 0 (все пакеты `ok`, гонок нет);
  - `BRIG_VERIFY=1 go test -count=1 ./...` → 0;
  - fuzz по 10 минут на цель (`-fuzztime=10m -parallel 4`): `FuzzLex` —
    26.3 M execs, ok; `FuzzParse` — 20.6 M execs, ok; `FuzzRoundTrip` —
    **падение на 195-й секунде**, вход `(fn->-0)` (G-22);
  - `make bench BENCH_COUNT=3` и собственные замеры скорости и асимптотики
    (X-1, X-4);
  - временные Go-тесты (в репозиторий не добавлены): round-trip форматтера
    по всем 111 разбираемым `.brig` репозитория плюс файл со всеми
    конструкциями волн 6–13 — 0 расхождений; сверка арностей всех 105
    нативов и stdlib-функций с таблицами спеки;
  - ~70 пробных программ `brig`, `brig check`, `brig test`, `brig -i -`,
    `brig -e`; каждая, короче 20 строк, приведена в своём finding;
  - стресс: 1 000 / 10 000 / 100 000 акторов, fan-in ответов, падение
    всех акторов с `watch`, 100 000 вложенных `trap`+`ensure`, рекурсия
    глубиной 10⁶, HTTP: 300 запросов в 50 потоков, граничные случаи
    `HttpServer`, graceful shutdown по SIGTERM;
  - три программы dogfooding (раздел 6, код — приложение A);
  - 28 ошибочных программ (e01…e28) и проба m1 для оценки диагностики (D-2);
  - `gh issue/pr/run list`, `gh project item-list` — доска, CI, bench- и
    fuzz-гейты, время жизни PR.
- **Не запускалось:** TTY-редактор REPL и TUI `observe()` (нужен
  терминал; проверены только режимы без TTY); замеры памяти Z1–Z6
  (стенд `bench-heap`, T-153 в Backlog); шаблоны `.bt` (парсера нет,
  research 15); многочасовой soak; Windows/macOS. Подробно — раздел 11.

## 2. Критерии «лучше»

Определены до предложений; каждое предложение (раздел 5) оценено по ним:
↑ улучшает, ↓ ухудшает.

| # | Критерий | Вес | Почему такой вес |
|---|---|---|---|
| K1 | **Корректность** — программа делает то, что обещает спека, во всех углах | 25 | Язык продаёт гарантии (иммутабельность, TCO, G1–G5, строгий `Bool`). Молча неверный результат обесценивает их все |
| K2 | **Производительность на целевых задачах** — сервисы и обработка данных из research | 15 | Цель research — web-MVP. Проигрыш «на порядок» важен только там, где он делает типовой код невозможным; так и есть (X-1) |
| K3 | **Выразительность для библиотек** — stdlib, Whelk, Calmar, `corpus/` | 15 | Фаза 1 research — «проектная база»; stdlib на Brig — главный контур качества языка |
| K4 | **Надёжность рантайма** — акторы, супервизия, HWM, TCO, сбои | 15 | Акторы — главное отличие Brig от Python и Go; дерево супервизии должно убирать за собой |
| K5 | **Предсказуемость** — читатель угадывает поведение без спеки (§0.1, §0.3) | 10 | Разрыв между «выглядит» и «делает» порождает тихие ошибки (K1) |
| K6 | **Опыт разработчика** — ошибки, `brig check/test`, REPL, путь новичка | 10 | Пользователи — пока авторы и агенты; опыт определяет, заметят ли они ошибку до рантайма |
| K7 | **Простота** — число понятий, один способ (§0.2) | 5 | Язык уже маленький; дубли дёшево убрать, но выигрыш невелик |
| K8 | **Сопровождаемость** — цена следующего изменения: код, тесты, доки, процесс | 5 | Темп высокий (≈370 коммитов за 8 дней); цена изменения уже мала, риск — дрейф документов |

Отправные точки промпта приняты все восемь; веса выбраны под текущую
стадию (pre-alpha → alpha, web-MVP).

## 3. Топ-10

Порядок — по ценности для продукта, не по слоям.

1. **Коллекции квадратичны — типовой код библиотек невозможен.**
   `List`, `Vector`, `Map`, `Set` — срезы Go, каждая «изменяющая» операция
   копирует всё: построение списка через `[x, ..acc]` на 8 000 элементах —
   4.7 с, на 16 000 — 44 с; `Map.put` 8 000 раз — 7.4 с; `Vec.push` — 4.0 с,
   хотя §4.4 обещает trie с O(1) amortized. Актор, держащий в стейте мапу
   на 10 000 сессий, тратит секунды на одно обновление. Это важнее всех
   микрооптимизаций и главное основание пересмотреть T-104 вместе с
   представлением коллекций. (X-1 → DD T-250, T-270…T-273)
2. **`brig test` не видит модулей проекта, доктесты не могут вернуть
   пользовательский тип.** Тестовый файл компилируется в одиночку, без
   загрузчика: `import Calc` в `calc_test.brig` даёт `undefined function
   Calc.add/2`. Модуль с `##`, который что-то импортирует, тоже не
   компилируется. Ответ доктеста считается на «чистой ВМ»: `Ok(Version{…})`
   → `неизвестный тип записи Version`. REPL-хелпер `v` затеняет `pub fn v`
   модуля. Контур F-4 работает только для `stdlib/`; в двух из трёх
   программ dogfooding ни один тест не запустился. (G-18, G-19 → T-244,
   T-245)
3. **Литерал `Map` хранит повторные ключи.** `%{"a" => 1, "a" => 2}` — мапа
   из двух пар с ключом `"a"`, `len` = 2; `%{1 => :int, 1.0 => :float}` —
   два «равных» ключа, `m[1.0]` → `:int`. `Map.put` при этом схлопывает.
   Молча неверное значение в самой частой структуре данных. (G-16 → T-241)
4. **Ответы теряются молча: HWM = 64 зашит в код.** Fan-in 1 000 воркеров
   к одному сборщику доставляет 65 ответов, остальные 935 — `Error(:busy)`,
   который никто не проверил; из 100 000 — 65. Порог не назван в спеке и
   не настраивается; §0.8 обещает «падение актора», а происходит тихая
   потеря у отправителя. (X-2 → DD T-251, T-274)
5. **Дерево супервизии оставляет сирот.** `link` ≡ `watch` (§12.2), поэтому
   убитый `exit(sup, :kill)` супервизор оставляет детей жить; то же при
   эскалации `:kill` от вышестоящего супервизора. Три способа наблюдать
   (`link`, `watch`, `spawn_linked`/`spawn_watched`) и ни одного способа
   «ребёнок умирает с родителем». (X-3 → DD T-252, T-275)
6. **`brig check` пропускает несвязанное имя и не знает режима
   `script`.** `print(y)` без `y` — `ok`, в рантайме `undefined: y` без
   позиции. Файл без `module` из одних `fn` молча ничего не делает:
   `fn main() -> print(1)` — пустой вывод и exit 0, ловушка первого
   запуска. (G-17, G-21, D-1 → T-242, T-243)
7. **Контуры обратной связи построены после кода и врут о прогрессе.**
   Сверка таблиц (T-118), `plan-check` (T-111), bench-гейт (T-152), fuzz
   и `-race` в CI (T-114) влиты 09-30 — после волн 9–15 (09-27…09-28);
   ловить им было нечего. `needs` корпуса и `pending` спеки ссылаются на
   закрытые задачи (11 файлов ждут закрытых T-135/T-137, три блока —
   закрытую T-126). Корпус измеряет отсутствие фреймворков горизонта, а не
   язык: первая ошибка 17 из 18 файлов — несуществующий модуль. (P-15,
   F-9…F-12 → T-246…T-249)
8. **Локальная `send = …` не затеняет примитив — молча шлёт сообщение.**
   `send = (a, b) -> (:mine, a, b)` и `send(self(), 2)` → `Ok(())`, при этом
   info «`send` shadows prelude binding» обещает обратное. То же для
   `spawn`, `reply`, `exit`. (G-20 → T-261)
9. **Нормативные документы отстают от кода.** Оператора `<>` (T-233) нет в
   `brig.ebnf`, в списке продолжений §2.2/§D.4 и операторах §B.1; §0.11 и
   §15.3 запрещают то, что реализовано (TCO сквозь `ensure`); §6.2
   описывает снятое ограничение (DD T-225 устарел). Спека — 3 510 строк,
   из них ~250 — история, версия v0.4.8 не менялась на 36 нормативных
   правках. (S-13…S-19 → T-240, DD T-258, T-259)
10. **Трение языка для библиотек — из dogfooding.** Нет `else if` и
    guard'ов в `match` (многоветочное условие — вложенные `if` или
    вспомогательная `fn`); `-x` не может начинать строку; `[2] < [1, 1]` —
    `true` (списки сравниваются сначала по длине); `print(1.0)` → `1`; нет
    `List.zip`, `sort_by`, `Map.to_list`, форматирования чисел; `Json.decode`
    возвращает ошибку строкой. (журнал трения → DD T-253…T-257, T-260,
    T-266, T-281, T-282)

## 4. Findings

Уровни: blocker / major / minor / nit. `[confirmed: …]` — команда или
проба; `[inferred: …]` — вывод без запуска. Блоки кода ниже — пробы
целиком, запуск `bin/brig <файл>` или `bin/brig check <файл>`.

### Слой P — процесс

**P-15 · major · Контуры обратной связи влиты после кода, который должны были проверять.**
- Где: `tasks/wave-7.md` («прежде чем менять язык…»), фактические даты
  merge: T-111 (`plan-check`) — 09-30 11:14, T-114 (fuzz/race в CI) — 09-30
  11:11, T-118 (таблицы спеки) — 09-30, T-152 (bench-гейт) — 09-30 16:40;
  волны 9–15 (T-130…T-224) — 09-27…09-28.
- Что не так: волны 9–15 (модули, stdlib, рантайм-механизмы, REPL,
  observer) прошли без сверки таблиц, без fuzz и `-race` в CI, без
  bench-гейта. Отсутствие сигналов у этих контуров — следствие порядка
  работ, а не их поломки. Первый же 10-минутный fuzz нашёл дефект (G-22).
- Тег: [confirmed: `git log --grep '\[T-NNN\]' --format=%ad` по задачам].
- Решение: план этого аудита ставит контуры в Wave 16 первыми, и новые
  контуры (T-246…T-249) — до задач языка и рантайма.

**P-16 · minor · Доска расходится с правилами.**
- DD T-174 (#291) закрыт как `COMPLETED` без записанного варианта (DoD
  DD: «вариант записан»); закрыт связанным PR, комментария с решением нет.
- T-237 (#373) не на доске.
- DD T-190…T-192 (#294–#296) стоят в Todo; `WORKFLOW.md` §2.2: новые DD —
  в Backlog до решения.
- Тег: [confirmed: `gh project item-list 5`, `gh api …/issues/291/timeline`].
- Решение: действия мейнтейнера (`tasks/wave-16.md`, «Перед Wave 16»).

**P-17 · minor · 148 worktree на 1.9 ГБ.**
- Где: skill `brig-workflow`, «Финиш» — нет шага `git worktree remove`.
- Тег: [confirmed: `git worktree list | wc -l` → 148; `du -sch ../brig-*`].
- Решение: строка в «Финиш» (T-246) и разовая чистка мейнтейнером.

**P-18 · minor · Ревью человеком фактически нет.**
- Медиана «PR открыт → merge» по 174 PR — 4 минуты, p90 — 50 минут;
  1 красный CI на ~100 PR (T-233, его поймал F-2).
- Что не так: `WORKFLOW.md` §7.1 требует до merge прочитать DoD, «НЕ
  делать» и diff golden-файлов, а §7.2 — режим «со сдачей на ревью» для
  всего, что трогает `compiler.go` и `scheduler.go`. За 4 минуты это не
  делается. Качество держится на CI и локальных прогонах агента.
- Тег: [confirmed: `gh pr list --state merged --json createdAt,mergedAt`].
- Решение: не вводить новый обязательный шаг ревью. Сделать так, чтобы CI
  проверял то, что человек не успевает прочитать (контуры Wave 16).
  Мейнтейнеру — привести §7.2 к фактическому режиму (действие в
  `wave-16.md`).

**P-19 · minor · Жёсткие счётчики в skills дрейфуют в третий раз.**
- `brig-overview:120`, `brig-testing-workflow:106` — `pending 4`, факт —
  `pending 3`. Второй аудит (P-9) фиксировал то же с `checked 62`.
- Решение: заменить на «failed 0» без чисел (T-246).

**P-20 · nit · Устаревшее в README, `architecture.md`, `WORKFLOW.md`.**
- README: «Спецификация языка (v0.4.7)», «`make fuzz` — 3 фаззера по
  60s», «`internal/prelude/doc.go` пуст», «один проход lexer → parser →
  ast → compiler → vm» (нет sema, loader), структура без `stdlib/`,
  `corpus/`, `internal/loader`, `highlight`, `observe`; нет ни одного
  примера кода.
- `architecture.md`: режимы без `script`, REPL «каждая строка»,
  «`Serialize()` вызывается при выходе за пределы общего хипа» (ложь,
  G-25), статус остановлен на Wave 6.
- `WORKFLOW.md` §7.3 и §8 хранят историю Wave 0, T-07, `iter/regvm`,
  #40–#43.
- Решение: T-240 (README, architecture), история `WORKFLOW.md` — в
  действиях мейнтейнера (правка `WORKFLOW.md` — docs-PR).

### Слой S — спека изнутри

**S-13 · major · Оператора `<>` нет в исполнительной грамматике и в лексической спеке.**
- Где: `brig.ebnf:91` (`pipe_expr ::= range_expr …` — уровня `<>` нет),
  `brig.ebnf:181` (`pattern_atom` без `"lit" <> pattern`); §2.2:175 и
  §D.4:2705 (список продолжений без `<>`); §B.1:2344 (операторы без `<>`);
  `brig.ebnf:1` — «Brig v0.4.7».
- Что не так: §A называет `brig.ebnf` исполнительной грамматикой; после
  T-233 она не описывает язык. Лексер `<>` как продолжение принимает
  (`internal/lexer/token.go:247`). Сверка T-118 проверяет ключевые слова,
  а операторы — нет, поэтому дрейф прошёл CI.
- Тег: [confirmed: grep; проба
  `fn main() ->⏎    s = "a"⏎        <> "b"⏎    print(s)` → `ab`].
- Решение: грамматика и §2.2/§D.4/§B.1 догоняют реализацию; сверка
  операторов в `make spec-tables` (T-240).

**S-14 · minor · §0.11 и §15.3 запрещают то, что реализовано.**
- §0.11: «VM гарантирует TCO… **кроме** вызовов внутри области активного
  `ensure`»; §15.3 — то же. §16 Should: «TCO сквозь `ensure` (…;
  реализовано, docs/02 §5.1)», T-173 влит.
- Тег: [confirmed: проба — 100 000 вложенных `trap` с `ensure` и хвостовым
  рекурсивным вызовом завершаются, кадров O(1)].
- Решение: правка принципа — DD T-258 (§0 меняет только человек).

**S-15 · minor · §6.2 «Ограничение реализации» устарело; DD T-225 тоже.**
- §6.2:651 — блочная полная лямбда в аргументах вызова «упирается в
  offside»; DD T-225 (#339) предлагает это снять.
- Тег: [confirmed:]
  ```
  module Main
  fn with_tx(f) -> f(:tx)
  fn main() ->
      r = with_tx(fn (tx) ->
          y = (tx, 1)
          y)
      print(r)
  ```
  → `(:tx, 1)`; так же `Test.it("…", fn ->⏎ блок)`.
- Решение: абзац удалить (T-240), #339 закрыть как сделанный в T-138
  (действие мейнтейнера).

**S-16 · minor · §8.1 якорь `else` противоречит §2.4.**
- §8.1:898 — «`else` на том же отступе, что `if` (якорь — токен `if`)»;
  §2.4 — якорь всех блоков `stmt_indent`, колонка открывателя не важна.
  Реализация следует §2.4: `x = if 1 > 0` … `else` на отступе строки `x =`
  работает.
- Тег: [confirmed: проба k5].
- Решение: §8.1 по §2.4 (T-240).

**S-17 · minor · Перенос строки внутри `\(...)`: спека разрешает, лексер запрещает.**
- §3.2:269 и §C.2:2518 — «физические переносы строк внутри `\(...)`
  допустимы»; комментарий §3.2:274 признаёт, что лексер их не
  поддерживает; пример §C.2 переноса не содержит.
- Тег: [confirmed: `x = "sum: \(1 +⏎2)"` → `unclosed interpolation '\(' (П-003)`].
- Решение: права реализация — перенос внутри интерполяции не нужен ни
  одной программе корпуса и dogfooding, форматтер его не порождает; спеку
  привести к ошибке лексера (T-240).

**S-18 · minor · Три `pending(T-126)` ссылаются на закрытую задачу.**
- §6.3:657, §9.3:991, §9.6:1024. T-126 (#185) закрыт; блоки падают по
  другой причине: два `fn main` в одном блоке, список выражений вместо
  паттернов.
- Тег: [confirmed: `make check-examples` → `pending 3`; `gh issue view 185`].
- Решение: блоки исправить (T-240), проверка закрытых задач — T-246.

**S-19 · minor · Спека — архив, версия не растёт.**
- 3 510 строк; Part III (H–L) — ~250 строк истории с «Итоговым статусом
  v0.4.7» и чек-листом «Практические шаги»; шапка — «Целевой этап: Трек
  B»; §17 — «не блокирует Трек B», «в v0.4.7»; §L — 36 нормативных
  пунктов под одной версией v0.4.8; T-233, T-171, T-173 в §L не
  записаны; строка §16 Must — одна ячейка на 1 400 символов.
- Что не так: читатель не отличает норму от истории; версия не сообщает,
  изменилась ли норма.
- Тег: [confirmed: чтение].
- Решение: DD T-259 (структура и версия), немедленная чистка шапки и §17 —
  T-240.

**S-20 · minor · §0.8 и §12.2 описывают разное переполнение; порога HWM в спеке нет.**
- §0.8: «Переполнение — контейнированное падение актора, наблюдаемое
  через `watch`». §12.2: `send` возвращает `Error(:busy)` отправителю,
  получатель жив. Число HWM (64, `internal/vm/scheduler.go:17`) спека не
  называет.
- Решение: DD T-251 (вместе с X-2).

**S-21 · minor · `Json.encode`/`Json.decode` не специфицированы.**
- §11.5:1409 — «`Json.encode`/`Json.decode` здесь не дублируются», но
  описания нет нигде: ни сигнатуры, ни результата `decode` (`Result`), ни
  маппинга `null`/`Option`/`Result`/записей, ни формы ошибок.
- Решение: DD T-256 (маппинг), T-266, справочник — T-280.

**S-22 · minor · Публичный API встроенных и stdlib-модулей без таблиц.**
- Без спецификации (есть только упоминания в прозе или `##` в
  `stdlib/`): `Map.get/put/keys/remove`, `Vec.get/set/push/len`,
  `Json.encode/decode`, `Record.to_anon`, `List.*` (10 функций),
  `Option.*`, `Result.*`, `Server.*`, `Supervisor.*`, `Behavior.spawn` —
  около 35 функций. Сверка T-118 проверяет только §11.5.
- Тег: [confirmed: временный тест сверки арностей — 105 функций, у 63
  нет строки в таблицах спеки; у 42 табличных арность совпадает].
- Решение: T-280 (справочник + сверка).

### Слой G — спека ↔ реализация

**G-16 · major · Литерал `Map` не схлопывает повторные ключи.**
- Где: `internal/vm/scheduler.go:1404-1414` (опкод `MAP` кладёт пары как
  есть), `internal/compiler/compiler.go:2278` (`compileMap`). Путь
  `Map.put` и спред `%{ ..m, k => v }` схлопывают.
- Что не так: §5.2 — «при повторе ключа побеждает правый»; §4.8 — `1` и
  `1.0` в ключах `Map` — один ключ.
- Тег: [confirmed:]
  ```
  module Main
  fn main() ->
      m = %{ 1 => :int, 1.0 => :float }
      print(len(m), m[1.0], len(%{ "a" => 1, "a" => 2 }))
      print(%{ "a" => 1, "a" => 2 })
  ```
  → `2 Some(:int) 2` и `%{"a" => 1, "a" => 2}`.
- Решение: права спека; `MAP` строит мапу тем же путём, что `Map.put`
  (T-241).

**G-17 · major · `brig check` не ловит ссылку на несвязанное имя.**
- Где: `internal/sema/names.go:14-18` — проход имён проверяет только
  вызовы; `internal/vm/scheduler.go:1035` — `undefined: y` в рантайме.
- Что не так: §F.3 — ошибка компиляции «вызов **или ссылка** на имя,
  которое не связано в области». Сейчас опечатка в имени переменной
  проходит `brig check` и падает в рантайме без `line:col`, exit 2.
- Тег: [confirmed: `module Main⏎fn main() ->⏎    print(y)` → `brig check`:
  `ok`; запуск: `brig: e02.brig: undefined: y`; то же `f = x -> x + zz`].
- Решение: права спека (T-242).

**G-18 · major · `brig test` компилирует файл в одиночку.**
- Где: `cmd/brig/test.go:145-162` (`loadTestModule`:
  `sema.CheckNames(prog, nil)`, `compiler.New().Compile(prog)` — без
  `internal/loader`).
- Что не так: §11.6 — тестовые функции и доктесты «каждого файла под
  path»; тестовый файл, который импортирует модуль проекта, и модуль с
  `##`, который импортирует другой модуль, не компилируются.
  Диагностика неверна: не «модуль не найден», а `undefined function
  Calc.add/2`, хотя функция есть и `pub`.
- Тег: [confirmed: `t/calc.brig` (`module Calc`, `pub fn add(a, b) -> a +
  b`) и `t/calc_test.brig` (`module CalcTest⏎import Calc⏎fn test_add() ->
  Test.assert_eq(Calc.add(1, 1), 2)`) → `brig test t` — `undefined
  function Calc.add/2`, `0 passed, 2 failed`; `brig t/main.brig` с тем же
  `import Calc` работает. Dogfooding: `brig test .` в проекте CSV — 3 из 3
  файлов с импортами не компилируются].
- Решение: права спека; `brig test` грузит программу загрузчиком, как
  `brig <file>` (T-244).

**G-19 · major · Доктест не может ответить значением пользовательского типа; хелперы REPL затеняют функции модуля.**
- Где: `internal/examples/examples.go:388` (`runRepl`: «ответ — на
  чистой [ВМ]»), §11.6:1463 («ответ — на отдельной чистой ВМ»),
  `internal/repl/helpers.go:50` (`v`), §11.4:1325 (хелперы голыми именами
  в режиме `repl`).
- Что не так: (1) доктест функции, которая возвращает запись или вариант
  своего модуля, невозможен: ответ `Ok(Version{ major: 1, … })` падает
  `неизвестный тип записи Version`; (2) во вводе доктеста голое имя
  хелпера (`v`, `h`, `i`, `load`, `time`, `info`, `top`, `tree`, …)
  побеждает `pub fn` модуля с тем же именем. §11.4 говорит только, что
  **связывание** во вводе затеняет хелпер; про функции загруженного
  модуля — ничего.
- Тег: [confirmed: `semver.brig` из приложения A: 3 из 5 доктестов —
  `неизвестный тип записи Version`; `## > satisfies?(v("1.4.2"), …)` →
  `raise (:type_error, (:v, "1.4.2"))`].
- Решение: ответ вычисляется на ВМ с загруженными декларациями модуля без
  привязок ввода; функции загруженного модуля затеняют хелперы, как
  связывание (T-245, правка §11.4, §11.6 в ней же). Research Q-docs-code
  предполагал `Test.isolated` — R-9.

**G-20 · major · Локальная привязка не затеняет акторный примитив.**
- Где: `internal/compiler/compiler.go:1984-1989` — затенение учитывается
  только для `fn` своего модуля (`cur.fns`); skill `brig-compiler:181`
  признаёт («затенение локальной переменной компилятор пока не
  учитывает»), issue нет.
- Что не так: §6.6 разрешает затенение, sema выдаёт info «`send` shadows
  prelude binding», а вызов идёт в примитив.
- Тег: [confirmed:]
  ```
  module Main
  fn main() ->
      send = (a, b) -> (:mine, a, b)
      print(send(self(), 2))
      spawn = x -> x + 1
      print(spawn(1))
  ```
  → `Ok(())` (сообщение ушло в собственный ящик), затем `raise:
  (:type_error, (:call, 1))`; `reply = (x) -> x * 2; reply(21)` — ошибка
  компиляции `reply требует 3 аргумента(ов)`.
- Решение: права спека (T-261).

**G-21 · minor · `brig check` не знает режима `script`; `script` с `fn main` молча пуст.**
- Где: `cmd/brig` (check парсит в режиме `module`), §11.3.
- Что не так: (1) script-файл с top-level инструкциями — `brig check` →
  `module top-level allows only module/import/alias/type/fn/pub fn, got
  LOWER_IDENT`, хотя `brig <file>` его исполняет; (2) файл без `module`,
  в котором только `fn`, `check` считает модулем (`ok`), а запуск —
  script, где `main` не вызывается: вывод пуст, exit 0.
- Тег: [confirmed: `fn main() -> print(1)` → `brig check`: `ok`, `brig`:
  пусто, exit 0; `x = 1⏎print(x)⏎y = nope(1)` → `check`: ошибка режима;
  запуск печатает `1`, затем `s1.brig:1:1: undefined: nope` — строка 1
  вместо 3].
- Решение: `check` выбирает режим так же, как запуск; info о
  невызываемом `main` в script (T-243).

**G-22 · minor · `-x` не может начинать строку; форматтер это порождает.**
- Где: `internal/lexer/token.go:243-248` (`+` и `-` в списке
  продолжений), `internal/ast/format.go:401-412` (полная лямбда — всегда
  блоком).
- Что не так: строка стейтмента, которая начинается с унарного минуса,
  читается как продолжение предыдущей и падает; форматтер печатает `(fn
  -> -0)` как блок `fn ->⏎    -0`, который не разбирается. Спека
  (§2.2) конфликт не называет.
- Тег: [confirmed: `FuzzRoundTrip`, вход `(fn->-0)` → `parse error 2:5:
  expected INDENT, got -`; `fn neg(x) ->⏎    print("negating", x)⏎    -x`
  → `continuation must be indented more than statement`].
- Решение: DD T-255 (синтаксис), затем T-262.

**G-23 · minor · `Float` печатается как `Int`.**
- Где: `internal/runtime/value.go:340-341` (`fmt.Sprintf("%v", v.Float)`).
- Что не так: `print(1.0)` → `1`, `to_str(1.0) == "1"`, `[1.0]` → `[1]`.
  Печатная форма теряет вид; доктест `> 3.0 / 3` с ответом `1` проходит
  (`1 == 1.0`), а читатель документации видит Int. `Json.encode(1.0)` →
  `1.0` — JSON вид различает, `print` нет.
- Тег: [confirmed: `brig -e 'print(1.0, to_str(1.0), [1.0])'` → `1 1 [1]`].
- Решение: печатная форма `Float` всегда с `.` или `e` (T-260).

**G-24 · minor · Ошибки JSON — строки; `null` ↔ `None` асимметричны.**
- Где: `internal/runtime/json.go:246-297`.
- Что не так: `Json.decode("nope")` → `Error("(:json_decode, \"invalid
  character …\")")` — текст терма в `Str`, паттерном не разобрать;
  `Json.encode(%{(1, 2) => 3})` → `(:json_encode_error, "(:json_encode,
  (:invalid_key, (1, 2)))")`. `Json.encode(None)` → `null`, а
  `Json.decode("null")` → `()`; `Ok(2)` кодируется как `2`.
- Тег: [confirmed: `brig -e` пробы].
- Решение: DD T-256 (маппинг), T-266.

**G-25 · minor · `runtime.Serialize` и `runtime.MFA` — мёртвый код против спеки.**
- Где: `internal/runtime/value.go:1067`, `:1146`. Вызовов вне тестов нет;
  `MFA` строит `Map` со `Str`, §13.1 — «дескриптор MFA — запись»;
  `architecture.md` утверждает, что `Serialize()` вызывается.
- Тег: [confirmed: `grep -rn 'Serialize(\|MFA(' --include=*.go`].
- Решение: удалить (T-277); сериализация — research Q-term (`Term`,
  горизонт).

**Известное и запланированное** (не новые findings, второй раз не
заводятся): коллизия локальных `fn` между блоками — T-238 (#379); форма
тега `:type_error` у функций модулей — T-236 (#372), у прелюдии — DD T-237
(#373); ошибки без имени в спеке (`:field_error`, `:unwrap`,
`:max_restarts`…) — T-234 (#360); представление `Value` — DD T-104
(#173); повтор замеров Z2–Z4 — T-153 (#275); открытые вопросы §17 —
T-190…T-195; ленивые `Stream` — DD T-226 (#340).

**G-26 · nit · `link(42)` бросает `(:type_error, (:watch, 42))`.** Таблица
§11.5 так и записана; тег выдаёт реализацию `link` через `watch`.
Решается вместе с DD T-252.

**G-27 · minor · `brig check` модуля проекта ищет импорты от своего каталога.**
- `brig check corpus/lookout/lib/lookout/monitors.brig` → `module
  Lookout.Repo not found`: корень — каталог файла (§11.1: «каталог
  входного файла программы»), а `brig -i .` ищет корень по
  `project.brig`. Не входной модуль проекта нельзя проверить отдельно.
- Тег: [confirmed: запуск].
- Решение: `brig check` берёт корень по `project.brig`, если он есть
  (T-243); `brig <file>` не меняется.

### Слой X — надёжность и производительность рантайма

**X-1 · blocker · Коллекции копируются целиком на каждую операцию.**
- Где: `internal/runtime/value.go:196-222` — `List`, `Vector`, `Map`,
  `Set` — `[]Value`/`[]MapEntry`; `Value` — 296 Б (T-104, #173).
  `[x, ..acc]`, `Map.put`, `Vec.push`, `Map.remove` — O(n) копия.
- Что не так: §4.4 обещает `Vector` «trie, O(1) amortized append,
  O(log32 n) чтение». Для `List` и `Map` спека сложности не обещает, но
  идиома «аккумулятор в хвостовой рекурсии» и «мапа в стейте актора»
  становится квадратичной. CPython с явным копированием списка
  (`acc = [i] + acc`) строит 16 000 элементов за 0.43 с, Brig — за 44 с.
- Тег: [confirmed: `perf1.brig` (приложение B), без параллельной
  нагрузки]:

  | Операция | 1 000 | 2 000 | 8 000 | 16 000 |
  |---|---|---|---|---|
  | `[n, ..acc]` в хвостовой рекурсии | 177 мс | 267 мс | 4 664 мс | 43 879 мс |
  | `Map.put(acc, n, n)` | 385 мс | 498 мс | 7 410 мс | 61 396 мс |
  | `Vec.push(acc, n)` | 141 мс | 188 мс | 3 960 мс | 27 713 мс |
  | разбор `[h, ..t]` (для сравнения) | 1 мс | 1 мс | 3 мс | 15 мс |

  ×4 элементов → ×17 времени.
- Решение: DD T-250 (персистентные структуры, вместе с T-104), затем
  T-270…T-273. Контур, который поймал бы это, — T-247.

**X-2 · major · HWM = 64 зашит в код; потери молчаливы.**
- Где: `internal/vm/scheduler.go:17` (`defaultHWM = 64`), лимиты `spawn`
  (§12.10) HWM не принимают.
- Что не так: типовой fan-in (воркер отвечает родителю `send(parent,
  (:pong, n))`) теряет всё сверх 64, если родитель не успел разобрать.
  Отправитель получает `Error(:busy)`, но в идиоматичном коде результат
  `send` не проверяется, и ни sema, ни рантайм об этом не сообщают
  (L17/T-177 — только для `_ <-` в `with`).
- Тег: [confirmed: `a2.brig` (приложение B): N воркеров, каждому
  `(:ping, 1)`, сбор с `after 3000` → 1 000: `(:timeout, 935, 65)`;
  10 000: `(:timeout, 9935, 65)`; 100 000: `(:timeout, 99935, 65)`].
- Решение: DD T-251 (порог, настройка, диагностика, текст §0.8), T-274.

**X-3 · major · Убитый супервизор оставляет детей.**
- Где: §12.2 (`link` ≡ `watch`, «автоматической эскалации… нет»),
  `stdlib/supervisor.brig` (дети — `spawn_linked` в акторе супервизора;
  `stop_child` → `exit(c, :kill)` по дедлайну).
- Тег: [confirmed:]
  ```
  module Main
  fn idle() ->
      recv
          _msg -> idle()
  fn main() ->
      sup = Supervisor.start({ strategy: :one_for_one, max_restarts: 3, within: 5000, children: [
          { name: :a, start: () -> spawn_linked(idle), restart: :permanent },
          { name: :b, start: () -> spawn_linked(idle), restart: :permanent },
      ] })
      exit(sup, :kill)
      recv
          _x -> ()
      after 100 -> ()
      print(Actor.list())
      Sys.halt(0)
  ```
  → `[#<pid 0>, #<pid 2>, #<pid 3>]`: супервизор мёртв, оба ребёнка живы.
- Что не так: вложенный супервизор, который родитель убивает по таймауту
  остановки, теряет поддерево — утечка акторов и портов (порт закрывается
  только со смертью владельца, §12.12).
- Решение: DD T-252, T-275.

**X-4 · minor · Вызов функции в ~3 раза медленнее CPython.**
- `fib(27)` — 334 мс (CPython 3 — 107 мс); хвостовой цикл
  `loop(n - 1, acc + 1)` 3·10⁶ итераций — 1.31 с (≈440 нс на итерацию);
  `list(1 to 1_000_000)` + `map` + `filter` — 1.5 с.
  `make bench`: `BenchmarkCall` — 862 µs/op, 257 allocs/op.
- Тег: [confirmed: `perf2.brig` (приложение B), без параллельной
  нагрузки; с fuzz параллельно — 755 мс].
- Решение: не блокер; первые два хот-спота по профилю — T-276, основной
  выигрыш ожидается от T-104 (DD). Research Q-perf ставит цели «не хуже
  Rails» — R-8.

**X-5 · — · Что выдержало нагрузку** (не finding, для полноты слоя):
TCO сквозь `ensure` — 100 000 уровней `trap`/`ensure` с хвостовым
вызовом; нехвостовая рекурсия глубиной 10⁶ — без переполнения (кадры в
куче); 100 000 акторов порождаются за 1.5 с; 1 000 и 10 000 акторов,
упавших с `raise`, — все `:down` доставлены, `Actor.list` после — только
main; `HttpServer`: 300 запросов в 50 потоков — все 200; `Port.write` до
`respond` и после 204 — `:type_error`; закрытие без `respond` и падение
обработчика — 500; SIGTERM → drain → exit 0; `-race` чисто;
`BRIG_VERIFY=1` на всех тестах и программах dogfooding — чисто.
REPL при ошибке в многострочном вводе (`brig -i -`: незакрытая скобка,
пустая ветка `match`, висящий `+`) печатает ошибку и исполняет
следующий ввод; сессия, привязки и `self()` сохраняются (§11.4); плохая
только позиция ошибки висящего `+` (D-2, e10).

### Слой R — research ↔ спека ↔ план

**R-8 · minor · Цели Q-perf несовместимы с X-1/X-4, и ничто их не меряет.**
- Research 19/Q-perf: «не хуже Rails и ≥ 50 % Phoenix на I/O», макро и
  память — ночью. Макро-бенчмарков нет, T-153 (повтор Z2–Z4) в Backlog,
  DD T-104 не решён.
- Решение: пересмотр порядка — T-104 решается вместе с DD T-250; цель
  Q-perf оставить, но первым шагом сделать асимптотику (T-247), а не
  проценты.

**R-9 · minor · Q-docs-code: доктесты «в `Test.isolated`» — в спеке «на чистой ВМ».**
- Research 22/Q-docs-code исполняет доктест в изолированном экземпляре
  рантайма **с кодом модуля**; спека T-149 выбрала «ответ — на чистой
  ВМ», что и дало G-19.
- Решение: T-245 возвращает смысл research без `Test.isolated`.

**R-10 · minor · L12: `Instant`/`Date`/`Duration` — Must в research, горизонт в спеке.**
- Второй аудит перенёс конфликт в горизонт, но research так и называет их
  Must для web-MVP. Dogfooding обошёлся `Time.monotonic_ms`.
- Решение: research — снимок (второй аудит, R-4), его не правят; норма —
  спека (§12.11, горизонт). Решение research этим фактически пересмотрено
  спекой; трассировка фиксирует статус. Новый DD не нужен, пока нет
  потребителя типов времени.

**R-11 · nit · Q-telemetry «реестр в `Global`» — §12.14 «через `Global.get`
не виден».** Спека решила иначе и точнее; research устарел, трассировка
это фиксирует.

### Слой F — контуры обратной связи

Реальные сигналы F-1…F-8 — раздел 7. Здесь — дефекты самих контуров.

**F-9 · major · `needs` и `pending` не знают, закрыта ли задача.**
- Где: `internal/corpus/corpus.go:243-247` («задачи нет в tasks/»),
  `internal/examples/examples.go:71` (`LoadTasks` — номер встречается в
  `tasks/*.md`).
- Что не так: закрытая задача остаётся «ожидаемой» навсегда, если файл
  ждёт ещё и `horizon`. Сейчас: у 11 файлов корпуса в `needs` закрытые
  T-135 и T-137, ещё у 9 — закрытые T-133, T-144, T-147, T-155,
  T-163…T-168; `make corpus` печатает «top needs: T-135 11, T-137 11» —
  приоритизация по закрытым задачам. Три `pending(T-126)` — S-18.
- Тег: [confirmed: `make corpus`; сверка с `gh issue list --state all`].
- Решение: проверка закрытых задач онлайн и CI-проверка на PR, который
  закрывает T-NNN (T-246).

**F-10 · major · Корпус измеряет отсутствие горизонта, а не язык.**
- Первая ошибка `brig check` у 17 из 18 файлов `lookout/` и `whelk/` —
  отсутствующий модуль (`Calmar.Endpoint`, `Sql`, `Http.Client`, `Env`,
  `Cli`, `Whelk`, `Changeset`) или соседний модуль проекта (G-27).
  `horizon` в `needs` у 24 из 25 fail-файлов. Ни одна задача языка не
  может поднять их уровень: метрика «файлы на уровне check/run»
  (`tasks/README.md`, «Метрика прогресса») застыла на `run 4, check 2`.
- Тег: [confirmed: `brig check` каждого файла корпуса].
- Решение: заглушки модулей горизонта с сигнатурами (`pub fn … ->
  raise((:horizon, …))`) и корень проекта — тогда `check` доходит до кода
  библиотеки (T-249). Плюс программы этого аудита в `corpus/apps`.

**F-11 · minor · Bench-гейт не видит асимптотику.**
- 8 прогонов `bench.yml` (с 09-30), 0 срабатываний; ни один бенчмарк не
  строит коллекцию длиннее ~100 элементов, поэтому X-1 гейт не поймает и
  его исправление не защитит.
- Решение: бенчмарки масштабирования (T-247).

**F-12 · minor · Нет контура качества диагностики.** Сообщения
проверяются только тестами конкретных задач; 7 из 28 ошибочных программ
и проба m1 получают сообщение без позиции, с неверной строкой или без подсказки
(D-2). Решение: корпус диагностик (T-248).

### Слой D — опыт разработчика

**D-1 · major · Первый запуск по README может молча ничего не сделать.**
- README не содержит ни одной строки кода на Brig, путь новичка — `make
  build` и `examples/hello.brig`. Естественная первая программа
  `fn main() -> print(1)` без `module Main` — script (§11.3), `main` не
  вызывается, вывод пуст, exit 0, `brig check` — `ok` (G-21).
- Тег: [confirmed: e25].
- Решение: info-диагностика (T-243) и пример в README (T-240).

**D-2 · minor · 7 из 28 сообщений об ошибках плохие, плюс m1.** Остальные 21 — с
`file:line:col` и понятным текстом (rebinding, табуляция, `undefined
function f/2`, pipe-запрет, `module Nope not found`, raise со stack
trace). Плохие:

| Проба | Код | Сообщение | Что не так |
|---|---|---|---|
| e02 | `print(y)`, `y` не связан | `brig: e02.brig: undefined: y` | нет позиции; должен ловить `check` (G-17) |
| e10 | `y = x +⏎        3` | `7:1: expected expression, got NEWLINE` | строка 7 вместо 5; нет подсказки «продолжение — ведущим оператором» (§2.2) |
| e11 | `f = (x) ->⏎        x + 1` | `5:1: expected expression, got NEWLINE` | §F.2 называет ошибку «блочное тело у короткой лямбды», сообщение — нет |
| e15 | `recv` без отправителя | `deadlock: all actors blocked` | нет позиции `recv` и имени актора |
| e24 | guard в ветке `match` | `4:16: expected '->', got when` | не сказано, что guard в `match` запрещён (§8.3) |
| e26 | `x = if true then 1` | `5:1: expected 'else', got NEWLINE` | позиция — конец файла (5:1), а не строка 3 |
| e28 | `fold([1, 2], (acc, x) -> acc + x, 0)` | `raise: (:type_error, (:call, 0))` | нет позиции и trace — ошибка внутри натива |
| m1 | `-x` первой строкой стейтмента | `continuation must be indented more than statement` | вводит в заблуждение (G-22) |

- Тег: [confirmed: программы e01…e28, m1; тексты — в таблице].
- Решение: корпус диагностик (T-248), исправление (T-265).

**D-3 · minor · Прелюдия занимает частые имена.** `reply`, `all`, `find`,
`set`, `list`, `log`, `exit`, `link`, `watch`, `await`, `map` — любое
локальное имя из этого списка даёт info (dogfooding: `reply`, `all`), а
для акторных — ещё и не работает (G-20). Решение: исправить G-20;
сокращение прелюдии — в DD T-257 (дубли).

## 5. Предложения

Формат: проблема и доказательства → изменение → критерии (↑/↓) →
альтернативы → цена → обратимость → кто решает. Правки §0, §16, DD и
research — только через DD (блоки — `tasks/decisions.md`).

### L-1 · Персистентные коллекции вместе с решением T-104

- **Проблема:** X-1 (квадратичные коллекции), T-104 (Value 296 Б), R-8.
  Журнал трения: #7, #8, #19.
- **Изменение:** `List` — неизменяемый односвязный список (или чанки с
  общим хвостом): `[x, ..xs]` и разбор `[h, ..t]` — O(1); `Vector` —
  32-арный trie (то, что §4.4 уже обещает); `Map`/`Set` — HAMT: `put`,
  `get`, `remove` — O(log₃₂ n). Спека получает таблицу гарантированной
  сложности (§4.2–§4.6). Миграция — одна вместе с вариантом B T-104
  (tagged `Value`), чтобы не переписывать `runtime`, прелюдию, JSON и
  REPL дважды.
- **Критерии:** K2 ↑↑, K3 ↑ (аккумуляторы, стейт-мапы), K4 ↑ (стейт
  акторов не деградирует); K8 ↓ (крупная миграция: `.List` — 69 мест в
  16 файлах, `.Map` — 29, `.Vector` — 27, `.Set` — 12), K1 риск ↓ на время
  миграции (term order, равенство, `KeyEqual`).
- **Альтернативы:** (B) только `List` — O(1) prepend, остальное
  задокументировать как O(n): дёшево, но стейт-мапы остаются
  квадратичными; (C) ничего, «строить через `map`/`fold`» в гайде: не
  лечит `Map.put`, противоречит §4.4.
- **Цена:** DD T-250; T-270 (спека сложности), T-271 (List), T-272
  (Map/Set), T-273 (Vector); тесты — существующие + T-247; `corpus/`,
  `stdlib/`, `examples/` не меняются (API тот же).
- **Обратимость и риск:** API не меняется — обратимо по коду; риск —
  регрессии равенства и порядка, ловятся `runtime`-тестами и fuzz.
- **Кто решает:** DD T-250.

### L-2 · Политика ящика: порог, настройка, видимость потерь

- **Проблема:** X-2, S-20; журнал #20.
- **Изменение:** HWM по умолчанию — 10 000; поле лимитов `spawn`
  `mailbox_hwm` (§12.10) задаёт его на актора; `send`, чей `Result`
  отброшен (стейтмент-выражение), — info sema «результат `send`
  игнорирован, `Error(:busy)` потеряется»; §0.8 переписан: «Переполнение —
  `Error(:busy)` у отправителя и событие `[:vm, :mailbox, :hwm]`;
  получатель жив».
  - было (§0.8): «**Рост очереди видим** (`mailbox_size`) и ограничен
    (HWM). Переполнение — контейнированное падение актора, наблюдаемое
    через `watch`.»
  - стало: «**Рост очереди видим** (`mailbox_size`) и ограничен (HWM,
    по умолчанию 10 000, настраивается при `spawn`). Переполнение —
    `Error(:busy)` у отправителя и событие `[:vm, :mailbox, :hwm]`;
    ящик получателя не растёт сверх порога.»
- **Критерии:** K1 ↑ (нет тихих потерь в типовом fan-in), K4 ↑, K5 ↑; K2 ↓
  (память под очередь: 10 000 × размер сообщения — ограничение на месте),
  K7 ↓ (ещё одно поле лимитов).
- **Альтернативы:** (B) оставить 64, только info на игнорированный
  `send` — потери останутся, но видны; (C) HWM без предела по умолчанию
  (Erlang) — нарушает §0.8.
- **Цена:** DD T-251, T-274 (`scheduler.go`, sema, §0.8, §12.2, §12.10).
- **Обратимость:** порог — константа; info — отключаемая диагностика.
- **Кто решает:** DD (§0).

### L-3 · `link` получает смысл: ребёнок умирает с родителем

- **Проблема:** X-3 (сироты), G-26; §0.2 — `link` ≡ `watch` без ref,
  `spawn_linked` ≡ `spawn_watched` без ref.
- **Изменение (рекомендация A):** `link(pid)`/`spawn_linked(f)` —
  однонаправленная связь «владелец → ребёнок»: смерть владельца по любой
  причине делает `exit(child, (:linked_exit, reason))` (не `raise`,
  `trap` не ловит, `ensure` выполняются, §12.7). Наблюдение за ребёнком —
  по-прежнему `watch`/`spawn_watched`. «Исключений через границы акторов»
  (§16 «Не надо») это не вводит: передаётся `exit`, а не ошибка.
- **Критерии:** K4 ↑↑ (дерево супервизии чистится само), K7 ↑ (у
  `link` появляется отдельный смысл), K5 ↑; K1 риск ↓ (меняется семантика
  существующего примитива), K8 ↓ (правка `scheduler.go`, §12.2, §12.7,
  stdlib-супервизора).
- **Альтернативы:** (B) удалить `link` и `spawn_linked` (§0.2), сирот
  лечить в `Supervisor` (дети следят за супервизором сами — лишний `watch`
  и `recv` в каждом ребёнке); (C) ничего — сироты остаются, документировать.
- **Цена:** DD T-252, T-275; `stdlib/supervisor.brig` (дети уже
  `spawn_linked` — поведение станет правильным без правки кода).
- **Обратимость:** средняя — программы, полагающиеся на выживание
  `spawn_linked`-детей, есть только в тестах VM.
- **Кто решает:** DD (§12, §16).

### L-4 · `else if` как сахар

- **Проблема:** журнал #1, #2 (многоветочные условия), проба k3: `else if`
  → `expected NEWLINE after else, got if`. Guard'ы разрешены только в `fn`
  и `recv` (§6.1), в `match` — нет (§8.3). Каждое трёхветочное условие —
  вложенный `if` на +1 уровень отступа или вспомогательная `fn`.
- **Изменение:** `else if cond` + блок — сахар для `else`⏎`if cond`;
  цепочка любой длины на одном уровне отступа; однострочная форма не
  меняется. `brig.ebnf`: `else_if_clause ::= "else" ( "if" expr NEWLINE
  INDENT stmt_list DEDENT [ else_if_clause ] | NEWLINE INDENT stmt_list
  DEDENT )`. Реализуется в парсере, компилятор не трогается.
- **Критерии:** K3 ↑, K6 ↑, K5 ↑ (так пишут Python, Ruby, Elixir `cond`);
  K7 ↓ (второй способ записать вложенный `if` — но с тем же AST).
- **Альтернативы:** (B) guard'ы в ветках `match` — мощнее, но спорит с
  §8.3 и чистотой `match`; (C) ничего.
- **Цена:** DD T-253, T-263 (парсер, форматтер, `brig.ebnf`, §8.1).
- **Обратимость:** полная (сахар).
- **Кто решает:** DD (синтаксис, §0.2).

### L-5 · Лексикографический порядок списков

- **Проблема:** журнал #16; проба: `[2] < [1, 1]` → `true`,
  `List.sort([[1, 1], [2], [0, 0, 0]])` → `[[2], [1, 1], [0, 0, 0]]`, а
  `"b" < "ab"` → `false`. §7.4 п.8–9 так и определяет (длина, затем
  элементы) для `List` и `Vector`. Версии, пути, ключи сортировки
  (`List.sort` по кортежам с `List` внутри) дают неожиданный порядок.
- **Изменение:** `List` и `Vector` — лексикографически (как `Str`,
  Erlang, Python, OCaml); кортежи — как сейчас (длина, затем элементы —
  так же в Erlang).
- **Критерии:** K5 ↑, K1 ↑ (сортировки в библиотеках); K2 ≈; K8 ↓ (term
  order — часть совместимости `Term`).
- **Альтернативы:** (B) оставить и описать в гайде; (C) лексикографически
  и кортежи — ломает сходство с Erlang без выигрыша.
- **Цена:** DD T-254, T-264 (`runtime.Compare`, §7.4, тесты).
- **Кто решает:** DD (§7.4 — принятый порядок DD #43).

### L-6 · Продолжение строки без `+` и `-`

- **Проблема:** G-22, D-2 (m1); `FuzzRoundTrip`.
- **Изменение (рекомендация A):** убрать `+` и `-` из списка продолжений
  §2.2/§D.4; строка, начинающаяся с `-`, — новый стейтмент с унарным
  минусом. Длинная арифметика переносится внутри скобок (§2.1: внутри
  скобок перенос свободен). Остальные операторы остаются.
- **Критерии:** K5 ↑, K1 ↑ (форматтер снова порождает валидный код), K6 ↑;
  K3 ↓ слабо (перенос `+` в начале строки — привычка Python/Black).
- **Альтернативы:** (B) оставить, форматтер скобит тело блока с ведущим
  минусом, ошибка объясняет «оберните в скобки» — конфликт остаётся в
  языке; (C) продолжение по `-` только с пробелом после — пробел
  становится значимым, против §2.3.
- **Цена:** DD T-255, T-262 (лексер, §2.2, §D.4, примеры, корпус — 0
  файлов с ведущим `+`/`-` [inferred: `rg -n '^\s+[-+] ' corpus stdlib
  examples` проверить в T-262]).
- **Кто решает:** DD (синтаксис).

### L-7 · JSON: маппинг и структурные ошибки

- **Проблема:** G-24, S-21; журнал #5.
- **Изменение (рекомендация):** `Json.decode(s) -> Result<V, (:json,
  reason)>`, `reason` — атом или кортеж (`:syntax`, `(:number, s)`,
  `:depth_limit`, `:trailing_data`); `null` ↔ `None` в обе стороны
  (`Some(v)` кодируется как `v`); `Ok`/`Error` в `encode` — ошибка
  `(:json, (:unsupported, v))`, а не молчаливая распаковка;
  `Json.encode` — `raise((:json, reason))`. Таблица маппинга в спеке.
- **Критерии:** K1 ↑, K5 ↑, K3 ↑; K8 ↓ (меняется поведение, которое код
  мог использовать: `null` → `()`).
- **Альтернативы:** (B) оставить `()` для `null` (как сейчас), только
  структурные ошибки; (C) ничего, описать текущее.
- **Цена:** DD T-256, T-266 (`runtime/json.go`, спека, тесты,
  `examples/json.brig`).
- **Кто решает:** DD (новая семантика + §0.4 «nil нет»).

### L-8 · Один способ: дубли stdlib и прелюдии

- **Проблема:** §0.2; журнал #12, #13; D-3. Дубли: `List.map/filter/fold`
  ≡ `map/filter/fold`; `Vec.len` ≡ `len`; `to_int(s)` (raise) и
  `Str.to_int(s)` (`Option`) — два способа разобрать число; `<>` и
  интерполяция для склейки строк (T-121 запретил `Str + Str` ради §0.2,
  T-233 добавил `<>`).
- **Изменение (рекомендация):** голые `map/filter/fold` прелюдии
  остаются (pipe §7.5, короче), `List.map/filter/fold` удаляются;
  `Vec.len` удаляется (есть `len`); `to_int`/`to_float` принимают только
  числа, разбор строк — `Str.to_int`/`Str.to_float` (`Option`); правило
  в §7.3a: `<>` — склейка строк, интерполяция — подстановка значений.
- **Критерии:** K7 ↑, K5 ↑; K8 ↓ (правка stdlib, спеки, тестов; `to_int`
  на `Str` — ломающая).
- **Альтернативы:** (B) оставить всё, записать в гайде, какой способ
  канонический; (C) убрать только `Vec.len` и `List.map/filter/fold`.
- **Цена:** DD T-257, T-267.
- **Кто решает:** DD (§0.2).

### L-9 · Принцип §0.11 по реализации

- **Проблема:** S-14.
- **Изменение:**
  - было: «**VM гарантирует TCO** для хвостовых вызовов, **кроме вызовов
    внутри области активного `ensure`**: код `ensure` обязан выполниться
    после возврата, что требует сохранения кадра.»
  - стало: «**VM гарантирует TCO** для хвостовых вызовов, в том числе
    внутри `trap` с `ensure`: кадр заменяется, а невыполненные `ensure`
    хранятся компактной записью в куче (O(1) кадров, O(n) памяти на n
    уровней `ensure`, docs/02 §5.1).» §15.3 и §16 (TCO сквозь `ensure` —
    из Should в Must) — так же.
- **Критерии:** K5 ↑, K1 ↑ (норма = поведение); K8 ↓ (гарантия
  становится обязательной для любой будущей реализации, в том числе N:M).
- **Альтернативы:** (B) оставить «кроме», реализацию считать
  необязательным бонусом эталона — спека снова расходится с кодом.
- **Цена:** DD T-258, T-268 (docs).
- **Кто решает:** DD (§0, §16).

### L-10 · Спека без истории; версия на каждую нормативную правку

- **Проблема:** S-19, P-20.
- **Изменение:** Part III (H–L), «Итоговый статус», «Практические шаги»
  переносятся в `docs/spec-history.md`; в спеке остаётся норма и короткий
  «Что изменилось в текущей версии». Нормативный PR поднимает версию
  (`v0.5.0` — первая после переноса; дальше `v0.5.N`), `brig.ebnf`
  носит ту же версию, `make spec-tables` сверяет. §16 — список по
  уровням вместо таблицы с ячейкой на 1 400 символов.
- **Критерии:** K8 ↑, K5 ↑, K6 ↑ (новичок читает норму); K8 ↓ слабо
  (ещё одна проверка версии в PR).
- **Альтернативы:** (B) только чистка шапки и §17 (T-240) — история
  продолжит расти; (C) генерировать changelog из git-cliff — теряются
  ссылки на DD.
- **Цена:** DD T-259, T-268.
- **Кто решает:** DD (структура нормативного документа).

### F-P1 · Контуры Wave 16 (крупное предложение слоя F)

- **Проблема:** P-15, F-9…F-12, P-18 (ревью человеком не успевает).
- **Изменение:** пять новых или исправленных контуров — раздел 7.2:
  гигиена `needs`/`pending` (T-246), асимптотика (T-247), диагностики
  (T-248), корпус с заглушками горизонта и приложениями аудита (T-249),
  сверка операторов спеки (T-240).
- **Критерии:** K8 ↑, K1 ↑ (дефекты находятся до merge), K6 ↑; K8 ↓ (CI
  дольше на ~1 мин).
- **Альтернативы:** обязательное ревью человеком (P-18) — дороже и не
  масштабируется на темп ~40 PR/день.
- **Цена:** задачи, в DD не нуждаются.
- **Кто решает:** задачи.

## 6. Журнал трения dogfooding

Три программы — приложение A: **KV-сервис** (181 строка: `HttpServer`,
`Supervisor`, `Behavior`, реестр, `Timer`, TTL, graceful shutdown), **CSV
и отчёт** (210 строк в четырёх файлах: парсер с кавычками, конвейер
`Result` по стадиям, чтение через порт `File`, доктесты, тест-файл),
**библиотека `Semver`** (193 строки: записи, варианты, `<>`-паттерны,
`##` с доктестами, потребитель с квалифицированными типами). Все три
работают (`brig`, `BRIG_VERIFY=1`); не работают их тесты (G-18, G-19).

| # | Программа | Хотел | Пришлось | Критерий |
|---|---|---|---|---|
| 1 | KV | guard в ветке `match` (`Some(item) when alive?(…)`) | `if` внутри ветки, ветка «нет ключа» продублирована | K3 |
| 2 | Semver, KV | трёхветочное условие | вложенный `if` или `fn` с guard'ами (`fn cmp(x, y) when x < y`) | K3, K6 |
| 3 | KV | `match trap(Json.decode(body))` | лишняя привязка `r = trap(…)`: `trap` только в RHS связывания (§10.2) | K6 |
| 4 | KV | локальное имя `reply` | info-шум, переименование в `answer` (D-3) | K6 |
| 5 | KV | `Json.decode` бросает или даёт `Error(reason)` | `Error(Str)` с текстом терма; тип результата пришлось узнавать пробой — в спеке нет (G-24, S-21) | K5, K6 |
| 6 | KV | прочитать тело запроса одной функцией | 8 строк `Port.request`/`recv` с тремя ветками (модуля `Http` нет — горизонт) | K3 |
| 7 | KV | отфильтровать мапу | `Map.keys` → `filter` → `fold` + `Map.put` + свой `unwrap(Map.get(…))`: нет `Map.filter`/`Map.to_list` | K3, K2 (квадратично, X-1) |
| 8 | CSV | сгруппировать по ключу | `fold` + `Map.put` + `Map.get_or` — квадратично (X-1) | K2, K3 |
| 9 | CSV | `List.zip`, `with_index` | свои `zip` и `index` с аккумулятором и `List.reverse` | K3 |
| 10 | CSV | деструктурировать пару в короткой лямбде `(m, (k, v)) ->` | `fn (m, (k, v)) -> …` — короткая лямбда только с именами (§6.2) | K3, K5 |
| 11 | CSV | `sort_by(fn)` по убыванию | ключ-кортеж `(0.0 - t.revenue, …)` + `List.sort` + распаковка | K3 |
| 12 | CSV | `Str.to_float` как `Str.to_int` | `trap(to_float(…))` + привязка + `match`; два стиля разбора чисел (L-8) | K7, K6 |
| 13 | CSV | формат `34.46` | своя `money` через `to_int(x * 100.0 + 0.5)`, свой `pad`: форматирования чисел и строк нет | K3 |
| 14 | CSV | `brig test .` в проекте | 3 из 4 файлов «не скомпилирован» из-за `import` (G-18) | K6, K1 |
| 15 | CSV, Semver | доктест `> Csv.parse(…)` в модуле `Csv` | только голые имена: квалифицированное имя своего модуля во вводе доктеста не видно; пример в доке не совпадает с вызовом у пользователя | K6 |
| 16 | Semver | сравнить pre-release идентификаторы как списки | `[2] < [1, 1]` → `true`; порядок по длине (L-5) | K5, K1 |
| 17 | Semver | `pub fn v(s)` — короткий конструктор версии | переименование в `ver`: хелпер REPL `v` побеждает в доктестах (G-19) | K6 |
| 18 | Semver | доктест `parse("1.2.3")` → `Ok(Version{…})` | невозможно: ответ на чистой ВМ (G-19) | K3, K6 |
| 19 | все | собрать список в цикле | `[x, ..acc]` + `List.reverse` — квадратично; для 10⁴ элементов — секунды (X-1) | K2 |
| 20 | стресс | fan-in ответов воркеров | 93–99.9 % ответов потеряны молча (X-2) | K1, K4 |
| 21 | Semver | аннотация `pre: List` (элементы `Int` или `Str`) | `List requires 1 type argument`, а `List<Any>` принят: аннотации «documentation-only» (§14.4), но арность проверяется, имена — нет | K5 |
| 22 | стресс | `Time.sleep(100)` | `recv`⏎`_x -> ()`⏎`after 100 -> ()` | K3 |
| 23 | все | константы модуля (`start_timeout_ms`) | функции без аргументов (так же в `stdlib/supervisor.brig`) | K3 |

Что понравилось (для раздела 9): `pattern = expr` с `(:badmatch, v)`;
`with` с `Some`/`Ok` вперемешку и `else` по видам ошибок; `"^" <> rest`
в клозах; record update с сохранением вида; частичные record-паттерны с
`as` и квалификацией (`Semver.Version{ major: 0 } as v`); конструкторы
как функции (`Result.map(parse(rest), Caret)`); `Supervisor` +
`Behavior` + `register` в 20 строк; pull-протокол портов — чтение файла и
тела запроса одним шаблоном; `Server.call` не трогает ящик вызывающего.

Не заработавших программ нет. Не заработали тесты двух из трёх программ
— это главный результат dogfooding (G-18, G-19).

## 7. Контуры обратной связи

### 7.1 Реальные сигналы F-1…F-8 за волны 9–13 и позже

| Контур | Когда влит | Сигналы | Вывод |
|---|---|---|---|
| F-1 корпус (T-115) | 09-27 | история `manifest.tsv`: уровни подняты T-138, T-139, T-143 (11 файлов `parse` → `check`), T-145, T-146, T-170, T-176, T-171 (+`lang/behavior.brig` на `run`); T-139 понизил ожидание `main.brig` (`run` → `check`: имена теперь ловит sema). Метрика «run/check» застыла: `run 4, check 2` | работает как регистратор, но не как сигнал: `horizon` и закрытые задачи в `needs` (F-9, F-10). Нужны заглушки и гигиена |
| F-2 `check-examples` (T-113, T-116, T-117) | 09-27 | единственный красный CI из ~100 PR — пример T-233 (`local fn` не в начале тела); `pending` следует за работой: рос с docs-PR T-160…T-162 (до 13), падал с feature-PR до 3 | **работает**. Дефект — `pending` на закрытую T-126 (S-18) |
| F-3 stdlib на Brig (T-146) | 09-28 | T-170 (`Supervisor`/`Server`) и T-171 (`Behavior`) написаны на Brig; по ходу найдены T-231 (голый член модуля в sema), T-232 (спред-вызов с захватом), T-236/T-237 (форма тега `:type_error`), T-238 (коллизия локальных `fn`) | **работает** — лучший источник багов языка |
| F-4 `brig test` (T-147) | 09-27 | 51 тест и доктест stdlib зелёные; в пользовательском проекте с `import` — не компилируется (G-18), ответы доктестов — только встроенные типы (G-19) | сломан за пределами `stdlib/` |
| F-5 таблицы спеки (T-118) | 09-30 | allowlist `raiseNotInSpec104` породил T-234 (5 имён ошибок без спеки); после Behavior добавлены `:no_handler`, `:bad_arity` | работает; не покрывает операторы (S-13) и API модулей (S-22) |
| F-6 bench-гейт (T-152) | 09-30 16:40 | 8 прогонов, 0 срабатываний | слишком молод и слеп к асимптотике (F-11) |
| F-7 `plan-check` (T-111) | 09-30 11:14 | ни одного срабатывания; `plan-check: 1 blocks, 180 table rows, 0 problems` | молод; не проверяет открытость задач |
| F-8 `brig check` имён (T-139) | 09-28 | T-139 понизил ожидание `corpus/lookout/lib/main.brig`; ловит `undefined function f/n`, приватность | неполон: переменные (G-17), `script` (G-21), корень проекта (G-27) |
| fuzz/`-race` в CI (T-114) | 09-30 | ночной fuzz ещё не запускался (cron 03:17 UTC); `-race` на PR — зелёный | локальный 10-мин прогон этого аудита нашёл G-22 за 195 с |

Контур, который ни разу ничего не поймал (F-6, F-7), — не сломан: он
появился после кода. F-4 и F-8 — сломаны по существу (см. G-17, G-18).

### 7.2 Новые и исправленные контуры

| # | Контур | Что ловит | Задача |
|---|---|---|---|
| N-1 | гигиена меток: `needs`/`pending(T-NNN)` на закрытую задачу — ошибка онлайн; PR с `[T-NNN]` не оставляет `T-NNN` в `needs`/`pending` | ложные «ждёт задачу», неверный топ приоритетов | T-246 |
| N-2 | бенчмарки масштабирования: t(8k)/t(1k) ≤ 16 для `[x, ..acc]`, `Map.put`, `Vec.push` | квадратичность коллекций и регресс после T-271…T-273 | T-247 |
| N-3 | корпус диагностик: ошибочная программа → ожидаемые `line:col` и подстрока | регресс и качество сообщений | T-248 |
| N-4 | заглушки горизонта + корень проекта в корпусе; приложения аудита в `corpus/apps` на уровне `run` и e2e | прогресс языка на коде библиотек, а не отсутствие фреймворков | T-249 |
| N-5 | сверка операторов: §B.1 = лексер = терминалы `brig.ebnf`; §2.2 = §D.4 = `continuationOps` | дрейф грамматики (S-13) | T-240 |
| N-6 | справочник API модулей ↔ код (как T-118 для §11.5) | недокументированные функции (S-22) | T-280 |

## 8. Трассировка research

Статус: **спека** — решение внесено; **задача** — есть issue или блок;
**отсрочка** — горизонт `tasks/README.md`; **пересмотр** — предлагается
изменить решение research.

| Решение | Статус | Где | Комментарий |
|---|---|---|---|
| Q-vis `pub fn` | спека, сделано | §11.2, T-143 | — |
| Q-mod `M.f` как значение | спека, сделано | §7.6, T-144 | модули и типы как значения — отсрочка |
| Q-poly «модуль типа» | отсрочка | — | — |
| L4 `rec.field`, `(:no_field, …)` | спека, сделано | §4.7, T-131 | `:field_error` у `User{ ..r }` — T-234 |
| L7 kwargs не вводить | спека | §16 «Не надо» | — |
| L9 `"""` | спека, сделано | §3.5, T-145 | — |
| L12 `Decimal` Must | спека | §16 | — |
| L12 `Instant`/`Date`/`Duration` Must | отсрочка; спека пересмотрела research (R-10) | §12.11 — горизонт | research — снимок, не правится |
| L13 or-паттерны | DD открыт | T-193 (#297) | — |
| L16 `Json.at`, `Map.get_or` | спека, сделано | §11.5, T-176 | — |
| L17 `_ <-` info | сделано | T-177 | расширить на `send` — L-2 |
| L18 update сохраняет вид | спека, сделано | §4.7, T-142 | — |
| L19 тип = последний сегмент | спека, сделано | §11.1, T-137 | — |
| L20 `_name` | спека, сделано | §1.2, T-132 | — |
| L21 `(:badmatch, v)` | спека, сделано | §5.1, T-133 | — |
| L22 лямбды | спека, сделано | §6.2, T-140, T-141 | ограничение §6.2 устарело (S-15) |
| L2 модули из файлов, циклы | спека, сделано | §11.1, T-135, T-137 | корень для `check` — G-27 |
| Q-quote-base | спека (резерв) | §1.3, T-132 | RFC-0001 — отсрочка |
| L24/Q-docs-code `##`, доктесты | спека, сделано частично | §11.6, §11.7, T-147, T-149 | **пересмотр** спеки к research: ответ с кодом модуля (R-9, T-245) |
| Q-contracts | отсрочка | — | §14.4 |
| Q-await | спека, сделано | §12.9, T-165 | — |
| Q-reg | спека, сделано | §12.8, T-164 | — |
| Q-exit | спека, сделано | §12.7, T-163 | — |
| R4 `spawn_watched` | спека, сделано | §12.7, T-163 | с `link` — DD T-252 |
| R6/R7 `Timer`, `Time` | спека, сделано | §12.11, T-166 | — |
| R13/B3 `Global` | спека, сделано | §12.11, T-167 | — |
| R1 внешние события, G5 | спека, сделано | §12.12, §15.2, T-168 | — |
| R2 порты, `File` | спека, сделано | §12.12, T-228 | — |
| B2/Q-http HTTP-сервер | спека, сделано | §12.12, T-229 | TLS, HTTP/2, клиент — отсрочка |
| R8/B7 бюджет хода | спека, сделано | §12.10, T-169 | `mailbox_hwm` в лимитах — L-2 |
| Q-telemetry | спека, сделано | §12.14, T-222 | «реестр в `Global`» — research устарел (R-11) |
| C7 observer | спека, сделано | §11.4, §12.13, T-221…T-224 | — |
| Q-script | спека, сделано | §11.3, T-207 | `brig check` script — G-21 |
| Q-perf бенчмарки | частично | T-152 | макро и память — отсрочка; асимптотика — T-247; **пересмотр** порядка (R-8) |
| Z-замеры, модель heap | DD открыт | T-104 (#173), T-153 (#275) | решать вместе с DD T-250 |
| Q-term (CBOR) | отсрочка | — | `runtime.Serialize` удалить (G-25) |
| Q-sched, B4 (DST) | спека | §15.2 | однопоточный детерминированный режим — не ломать |
| Q-pkg, Q-manifest, Q-cross, B5 | отсрочка | — | — |
| B1 ACME, Q-db, Q-data, Q-tpl, Q-routing, Q-auth | отсрочка | — | заглушки в корпусе — T-249 |
| L15 dev-reload | отсрочка | — | `recompile()` — T-210 сделан |
| Q-rfc | отсрочка | — | — |

## 9. Что сделано хорошо и что нельзя сломать

**Хорошо:**
- Ядро выдерживает нагрузку и граничные случаи: X-5 — TCO сквозь
  `ensure` на 10⁵ уровнях, рекурсия 10⁶, 10⁵ акторов, HTTP под
  конкуренцией, graceful drain. Каждая проба §12.7–§12.14 совпала со
  спекой.
- Fuzz лексера и парсера — 47 M выполнений без падений; `-race` и
  `BRIG_VERIFY=1` чисты на всём наборе.
- Форматтер — 0 расхождений round-trip на 111 файлах и на всех
  конструкциях волн 6–13 (кроме G-22).
- Спека в части рантайма — одна из самых точных, что встречались:
  порты, HTTP, `exit`, `await`, телеметрия описаны до уровня отказов и
  лимитов, и реализация им следует.
- F-2 и F-3 — настоящие контуры: F-2 — единственный красный CI, F-3
  (stdlib на Brig) нашёл 5 багов языка.
- Процесс: DD с вариантами, `tasks/` с блоками и `plan-check`, пробы с
  воспроизведением, стек PR с описанным порядком merge.
- Диагностика: 21 из 28 ошибочных программ получает `file:line:col` и
  понятный текст; stack trace у raise.
- Dogfooding-код читается хорошо: `with`, `pattern = expr`, `<>` в
  клозах, record update, `Supervisor`/`Behavior`.

**Нельзя сломать:**
- однопоточный детерминированный run-loop как режим (research B4) и
  гарантии G1–G5;
- строгий `Bool`, отсутствие `nil`, иммутабельность;
- `pattern = expr` с `(:badmatch, v)` и ловимость всех `:type_error`;
- приватность по умолчанию и `pub`;
- pull-протокол портов (§12.12) и `await` по ref-слоту мимо ящика;
- `check-examples` с компиляцией и исполнением REPL-блоков;
- `stdlib/` на Brig как первый потребитель языка.

## 10. Сводная таблица «finding / предложение → задача или DD»

| ID | Уровень | Кратко | Задача / DD |
|---|---|---|---|
| X-1, L-1 | blocker | коллекции квадратичны | DD T-250 → T-270…T-273; контур T-247 |
| G-18 | major | `brig test` без загрузчика | T-244 |
| G-19, R-9 | major | доктесты: чистая ВМ, хелперы затеняют модуль | T-245 |
| G-16 | major | повторные ключи в литерале `Map` | T-241 |
| X-2, S-20, L-2 | major | HWM 64, тихие потери, §0.8 | DD T-251 → T-274 |
| X-3, G-26, L-3 | major | сироты супервизора, `link` ≡ `watch` | DD T-252 → T-275 |
| G-17 | major | несвязанное имя проходит `check` | T-242 |
| G-20 | major | локальная привязка не затеняет примитив | T-261 |
| D-1, G-21, G-27 | major / minor | `script` и `check`, корень проекта | T-243; README — T-240 |
| P-15, F-P1 | major | контуры после кода | Wave 16 первой |
| F-9 | major | `needs`/`pending` на закрытые задачи | T-246 |
| F-10 | major | корпус меряет горизонт | T-249 |
| S-13 | major | `<>` нет в `brig.ebnf`, §2.2, §B.1 | T-240 |
| S-14, L-9 | minor | §0.11 против реализации | DD T-258 → T-268 |
| S-15 | minor | §6.2 ограничение, DD T-225 устарел | T-240; закрыть #339 |
| S-16, S-17, S-18 | minor | якорь `else`, перенос в `\(`, `pending(T-126)` | T-240 |
| S-19, L-10 | minor | спека-архив, версия | DD T-259 → T-268 |
| S-21, G-24, L-7 | minor | JSON не описан, ошибки строкой | DD T-256 → T-266 |
| S-22 | minor | API модулей без таблиц | T-280 |
| G-22, L-6 | minor | `-x` не начинает строку; fuzz | DD T-255 → T-262 |
| G-23 | minor | `print(1.0)` → `1` | T-260 |
| G-25 | minor | мёртвые `Serialize`/`MFA` | T-277 |
| L-4 | предложение | `else if` | DD T-253 → T-263 |
| L-5 | предложение | порядок списков | DD T-254 → T-264 |
| L-8, D-3 | предложение | дубли §0.2, имена прелюдии | DD T-257 → T-267 |
| X-4 | minor | вызовы в 3 раза медленнее CPython | T-276; T-104 |
| F-11 | minor | bench слеп к асимптотике | T-247 |
| F-12, D-2 | minor | диагностики | T-248 → T-265 |
| P-16 | minor | доска: T-174, T-237, DD в Todo | действия мейнтейнера |
| P-17 | minor | 148 worktree | T-246 (skill), мейнтейнер |
| P-18 | minor | ревью 4 минуты | действия мейнтейнера (§7.2), F-P1 |
| P-19 | minor | счётчики в skills | T-246 |
| P-20 | nit | README, architecture, WORKFLOW | T-240; мейнтейнер |
| R-8 | minor | Q-perf и порядок | DD T-250 |
| R-10, R-11 | minor / nit | research устарел | трассировка (раздел 8) |
| журнал #9, #11, #13 | трение | нет `zip`, `sort_by`, форматирования | T-281, T-282 |
| — | — | `compiler.go` 4 043 строки, правки только по одной | T-269 |

## 11. Что не покрыто

- **TTY:** редактор строки, история, подсветка, Tab (T-202, T-203, T-211)
  и TUI `observe()` (T-224) — нужен терминал; проверены `brig -i -`,
  хелперы и нумерация `v(n)` без TTY.
- **Память:** Z1–Z6 (`bench-heap`) не перезапускались — T-153 в Backlog;
  RSS 10⁵ акторов не мерялся.
- **Шаблоны `.bt`** — парсера нет (research 15), только перечислены в
  манифесте.
- **Многочасовой soak** (утечки при долгой работе HTTP) — не запускался.
- **`recompile()`** (T-210) и загрузка проекта `brig -i .` — только
  справка и одна проба без проекта.
- **Платформы** — только linux/amd64.
- **Ночной fuzz в CI** — ещё не запускался (cron); здесь заменён
  локальным 10-минутным прогоном.
- **Корпус research `demo/`** — через `corpus/` (T-115), отдельно не
  прогонялся.

---

## Приложение A. Программы dogfooding

Исходники ниже — финальные версии, с которыми сделаны выводы раздела 6.
Перенос в `corpus/apps/` — T-249.

<details>
<summary>A.1 KV-сервис — <code>kv/main.brig</code> (181 строка)</summary>

```text
## KV-сервис: HTTP API поверх актора-хранилища.
##
##   brig main.brig [addr]
##   curl -X PUT localhost:4000/kv/a -d '{"value": 1, "ttl_ms": 5000}'
##   curl localhost:4000/kv/a
##   curl localhost:4000/stats
##
## Хранилище — Behavior под супервизором; раз в секунду таймер чистит
## просроченные ключи; SIGTERM/SIGINT — graceful shutdown.
module Main

# ---------- хранилище ----------

fn now() -> Time.monotonic_ms()

fn store_behavior() ->
    Behavior{
        handlers: %{
            :get => fn (st, key) ->
                found = Map.get(st.items, key)
                if alive?(found, now())
                    (Ok(unwrap(found).value), st)
                else
                    (Error(:not_found), { ..st, misses: st.misses + 1 })
            :put => fn (st, key, value, ttl) ->
                item = { value: value, expires: expiry(ttl) }
                (Ok(()), { ..st, items: Map.put(st.items, key, item), writes: st.writes + 1 })
            :delete => fn (st, key) ->
                (Ok(()), { ..st, items: Map.remove(st.items, key) })
            :sweep => fn (st) ->
                t = now()
                live = sweep(st.items, t)
                (len(st.items) - len(live), { ..st, items: live })
            :stats => fn (st) ->
                (Ok({ keys: len(st.items), writes: st.writes, misses: st.misses }), st)
        }
    }

fn expiry(None) -> None
fn expiry(Some(ms)) -> Some(now() + ms)

fn sweep(items, t) ->
    keep = filter(Map.keys(items), k -> alive?(Map.get(items, k), t))
    fold(keep, %{}, (acc, k) -> Map.put(acc, k, unwrap(Map.get(items, k))))

fn alive?(Some({ expires: None }), _t) -> true
fn alive?(Some({ expires: Some(e) }), t) -> e > t
fn alive?(None, _t) -> false

fn unwrap(Some(x)) -> x

fn start_store() ->
    pid = spawn_behavior(store_behavior(), { items: %{}, writes: 0, misses: 0 })
    Ok(()) = register(:store, pid)
    pid

fn store() ->
    match whereis(:store)
        Some(pid) -> Ok(pid)
        None -> Error(:store_down)

fn call(msg) ->
    with
        Ok(pid) <- store()
        Ok(answer) <- Server.call(pid, msg, 1000)
        answer
    else
        Error(e) -> Error(e)

# ---------- чистильщик ----------

fn sweeper() ->
    _ = Timer.send_after(1000, self(), :tick)
    recv
        :tick ->
            _ = call(:sweep)
            sweeper()

# ---------- HTTP ----------

fn route(:get, ["kv", key], _body) -> kv_get(key)
fn route(:put, ["kv", key], body) -> kv_put(key, body)
fn route(:delete, ["kv", key], _body) -> kv_delete(key)
fn route(:get, ["stats"], _body) -> stats()
fn route(_m, _path, _body) -> (404, %{ "error" => "not_found" })

fn kv_get(key) ->
    match call((:get, key))
        Ok(v) -> (200, %{ "key" => key, "value" => v })
        Error(:not_found) -> (404, %{ "error" => "no such key" })
        Error(e) -> (503, %{ "error" => to_str(e) })

fn kv_put(key, body) ->
    with
        Ok(json) <- decode(body)
        Some(v) <- Json.at(json, ["value"])
        Ok(()) <- call((:put, key, v, Json.at(json, ["ttl_ms"])))
        (201, %{ "key" => key })
    else
        None -> (400, %{ "error" => "value required" })
        Error(e) -> (400, %{ "error" => to_str(e) })

fn decode(body) ->
    match Json.decode(body)
        Ok(v) -> Ok(v)
        Error(_) -> Error(:bad_json)

fn kv_delete(key) ->
    match call((:delete, key))
        Ok(()) -> (204, %{})
        Error(e) -> (503, %{ "error" => to_str(e) })

fn stats() ->
    match call(:stats)
        Ok(s) -> (200, s)
        Error(e) -> (503, %{ "error" => to_str(e) })

fn split_path(path) -> filter(Str.split(path, "/"), s -> s != "")

# Тело запроса целиком: pull по порциям до :port_eof.
fn read_body(req, acc) ->
    Ok(()) = Port.request(req)
    recv
        (:port_data, p, chunk) when p == req -> read_body(req, Bytes.concat(acc, chunk))
        (:port_eof, p) when p == req -> Ok(acc)
        (:port_error, p, reason) when p == req -> Error(reason)
    after 5000 -> Error(:timeout)

fn handler() ->
    recv
        (:serve, req, head) ->
            match read_body(req, b"")
                Ok(bytes) ->
                    (status, payload) = route(head.method, split_path(head.path), Bytes.to_str(bytes))
                    respond(req, status, payload)
                Error(_) -> Port.close(req)

fn respond(req, 204, _payload) ->
    _ = HttpServer.respond(req, 204, [])
    Port.close(req)
fn respond(req, status, payload) ->
    _ = HttpServer.respond(req, status, [("content-type", "application/json")])
    _ = Port.write(req, Json.encode(payload))
    Port.close(req)

fn accept_loop(listener, sig, n) ->
    Ok(()) = Port.request(listener)
    recv
        (:http_request, l, req, head) when l == listener ->
            pid = spawn(handler)
            Ok(()) = Port.give(req, pid)
            _ = send(pid, (:serve, req, head))
            accept_loop(listener, sig, n + 1)
        (:signal, s, name) when s == sig ->
            print("got \(name), draining after \(n) requests")
            Port.close(listener)
            Port.close(sig)
            :stopped
        (:port_error, l, reason) when l == listener ->
            Port.close(sig)
            raise((:listen, reason))

fn main() ->
    addr = match Sys.args()
        [a, ..] -> a
        [] -> "localhost:4000"
    sup = Supervisor.start({
        strategy: :one_for_one,
        max_restarts: 5,
        within: 10_000,
        children: [
            { name: :store, start: () -> start_store(), restart: :permanent },
            { name: :sweeper, start: () -> spawn_linked(sweeper), restart: :permanent },
        ],
    })
    sig = Signal.subscribe([:sigterm, :sigint])
    listener = HttpServer.listen(addr)
    print("listening on \(addr)")
    result = accept_loop(listener, sig, 0)
    Ok(()) = Supervisor.stop(sup, :shutdown, { timeout: 2000 })
    print("bye", result)
```

</details>

<details>
<summary>A.2 CSV и отчёт — <code>csv/*.brig</code> (210 строк)</summary>

```text
# ==== csv.brig ====
## CSV (RFC 4180, подмножество): поля через запятую, кавычки `"`,
## удвоенная кавычка внутри поля, перевод строки `\n` или `\r\n`.
##
## ```brig repl
## > parse("a,b\n1,2\n")
## Ok([["a", "b"], ["1", "2"]])
## > parse("x,\"y, z\"\n")
## Ok([["x", "y, z"]])
## > parse("\"a\"\"b\"")
## Ok([["a\"b"]])
## > parse("\"open")
## Error((:unclosed_quote, 1))
## ```
module Csv

## Разбирает текст целиком. `Ok(rows)` — список строк, строка — список
## полей `Str`; `Error((:unclosed_quote, line))` — кавычка не закрыта.
pub fn parse(text) ->
    chars = Str.split(text, "")
    parse_rows(chars, 1, [], [], "", :field_start)

# Автомат по кодпоинтам. Состояния: :field_start, :unquoted, :quoted,
# :quote_in_quoted. Поле копится в cur, строка — в row, строки — в rows
# (в обратном порядке, разворот в конце).
fn parse_rows([], line, rows, row, cur, :quoted) -> Error((:unclosed_quote, line))
fn parse_rows([], _line, rows, [], "", :field_start) -> Ok(List.reverse(rows))
fn parse_rows([], _line, rows, row, cur, _st) ->
    Ok(List.reverse([List.reverse([cur, ..row]), ..rows]))

fn parse_rows(["\"", ..rest], line, rows, row, "", :field_start) ->
    parse_rows(rest, line, rows, row, "", :quoted)
fn parse_rows(["\"", ..rest], line, rows, row, cur, :quoted) ->
    parse_rows(rest, line, rows, row, cur, :quote_in_quoted)
fn parse_rows(["\"", ..rest], line, rows, row, cur, :quote_in_quoted) ->
    parse_rows(rest, line, rows, row, cur <> "\"", :quoted)
fn parse_rows([c, ..rest], line, rows, row, cur, :quoted) ->
    next_line = if c == "\n" then line + 1 else line
    parse_rows(rest, next_line, rows, row, cur <> c, :quoted)

fn parse_rows([",", ..rest], line, rows, row, cur, _st) ->
    parse_rows(rest, line, rows, [cur, ..row], "", :field_start)
fn parse_rows(["\r", "\n", ..rest], line, rows, row, cur, st) ->
    parse_rows(["\n", ..rest], line, rows, row, cur, st)
fn parse_rows(["\n", ..rest], line, rows, row, cur, _st) ->
    parse_rows(rest, line + 1, [List.reverse([cur, ..row]), ..rows], [], "", :field_start)
fn parse_rows([c, ..rest], line, rows, row, cur, _st) ->
    parse_rows(rest, line, rows, row, cur <> c, :unquoted)

## Строки с заголовком → список записей-мап `Str → Str`.
##
## ```brig repl
## > with_header([["a", "b"], ["1", "2"]])
## Ok([%{"a" => "1", "b" => "2"}])
## > with_header([["a"], ["1", "2"]])
## Error((:width, 2))
## > with_header([])
## Error(:no_header)
## ```
pub fn with_header([]) -> Error(:no_header)
pub fn with_header([header, ..rows]) ->
    w = len(header)
    Result.all(map(index(rows, 0, []), pair -> row_map(header, w, pair)))

fn row_map(header, w, (row, i)) ->
    if len(row) == w
        Ok(fold(zip(header, row, []), %{}, fn (m, (k, v)) -> Map.put(m, k, v)))
    else
        Error((:width, i + 2))

# Нет List.zip и List.with_index в stdlib — свои.
fn zip([a, ..xs], [b, ..ys], acc) -> zip(xs, ys, [(a, b), ..acc])
fn zip(_, _, acc) -> List.reverse(acc)

fn index([], _i, acc) -> List.reverse(acc)
fn index([x, ..xs], i, acc) -> index(xs, i + 1, [(x, i), ..acc])

# ==== report.brig ====
## Сводка продаж из CSV: `region,product,qty,price`.
##
## Конвейер: текст → строки (`Csv.parse`) → записи (`Csv.with_header`)
## → типизированные `Sale` (`to_sale`) → группировка по региону →
## итоги. Любая ошибка останавливает конвейер и возвращается как
## `Error((stage, detail))`.
module Report

import Csv

type Sale { region: Str, product: Str, qty: Int, price: Float }

type Total { region: Str, orders: Int, units: Int, revenue: Float }

## Полный конвейер от текста до итогов по регионам (по убыванию выручки).
pub fn build(text) ->
    with
        Ok(rows) <- tag(:csv, Csv.parse(text))
        Ok(recs) <- tag(:header, Csv.with_header(rows))
        Ok(sales) <- tag(:row, Result.all(map(recs, to_sale)))
        Ok(sort_desc(totals(sales)))
    else
        Error(e) -> Error(e)

fn tag(stage, Ok(v)) -> Ok(v)
fn tag(stage, Error(e)) -> Error((stage, e))

## Запись CSV → `Sale`. Числа проверяются.
##
## ```brig repl
## > to_sale(%{"region" => "eu", "product" => "x", "qty" => "2", "price" => "1.5"})
## Ok(Sale{ region: "eu", product: "x", qty: 2, price: 1.5 })
## > to_sale(%{"region" => "eu", "product" => "x", "qty" => "two", "price" => "1.5"})
## Error((:qty, "two"))
## ```
pub fn to_sale(rec) ->
    with
        Some(region) <- Map.get(rec, "region")
        Some(product) <- Map.get(rec, "product")
        Ok(qty) <- int_field(rec, "qty")
        Ok(price) <- float_field(rec, "price")
        Ok(Sale{ region: region, product: product, qty: qty, price: price })
    else
        None -> Error(:missing_column)
        Error(e) -> Error(e)

fn int_field(rec, name) ->
    raw = Map.get_or(rec, name, "")
    match Str.to_int(Str.trim(raw))
        Some(n) -> Ok(n)
        None -> Error((to_atom(name), raw))

fn float_field(rec, name) ->
    raw = Map.get_or(rec, name, "")
    r = trap(to_float(Str.trim(raw)))
    match r
        Ok(f) -> Ok(f)
        Error(_) -> Error((to_atom(name), raw))

# Нет Str → Atom: имена колонок — фиксированный набор.
fn to_atom("qty") -> :qty
fn to_atom("price") -> :price
fn to_atom(_) -> :field

## Итоги по регионам.
pub fn totals(sales) ->
    groups = fold(sales, %{}, (acc, s) -> Map.put(acc, s.region, [s, ..Map.get_or(acc, s.region, [])]))
    map(Map.keys(groups), r -> total(r, Map.get_or(groups, r, [])))

fn total(region, sales) ->
    Total{
        region: region,
        orders: len(sales),
        units: fold(sales, 0, (a, s) -> a + s.qty),
        revenue: fold(sales, 0.0, (a, s) -> a + s.qty * s.price),
    }

fn sort_desc(ts) ->
    keyed = map(ts, t -> (0.0 - t.revenue, t.region, t))
    map(List.sort(keyed), fn ((_, _, t)) -> t)

## Таблица для печати.
pub fn render(ts) ->
    lines = map(ts, t -> "\(pad(t.region, 8)) \(pad(to_str(t.orders), 6)) \(pad(to_str(t.units), 6)) \(money(t.revenue))")
    Str.join(["region   orders units  revenue", ..lines], "\n")

fn pad(s, w) when len(s) >= w -> s
fn pad(s, w) -> pad(s <> " ", w)

# Нет форматирования чисел: два знака после точки руками.
fn money(x) ->
    cents = to_int(x * 100.0 + 0.5)
    "\(cents div 100).\(two(cents rem 100))"

fn two(n) when n < 10 -> "0\(n)"
fn two(n) -> to_str(n)

# ==== main.brig ====
## brig main.brig sales.csv
module Main

import Report

fn read_all(port, acc) ->
    _ = Port.request(port)
    recv
        (:port_data, p, chunk) when p == port -> read_all(port, Bytes.concat(acc, chunk))
        (:port_eof, p) when p == port -> Ok(acc)
        (:port_error, p, reason) when p == port -> Error(reason)

fn main() ->
    path = match Sys.args()
        [p] -> p
        _ -> "sales.csv"
    match read_all(File.open(path, :read), b"")
        Ok(bytes) ->
            match Report.build(Bytes.to_str(bytes))
                Ok(ts) -> print(Report.render(ts))
                Error(e) ->
                    eprint("bad input:", e)
                    Sys.halt(1)
        Error(reason) ->
            eprint("cannot read \(path):", reason)
            Sys.halt(1)

# ==== report_test.brig ====
module ReportTest

import Report

fn test_build_ok() ->
    Ok([t]) = Report.build("region,product,qty,price\neu,x,2,1.5\n")
    Test.assert_eq(t.revenue, 3.0)

fn test_build_bad_width() ->
    Test.assert_eq(Report.build("a,b\n1\n"), Error((:header, (:width, 2))))

fn test_quoted_field() ->
    Test.it("quoted comma", () -> Test.assert_eq(len(Report.totals([])), 0))
```

</details>

<details>
<summary>A.3 Библиотека Semver — <code>semver/*.brig</code> (193 строки)</summary>

```text
# ==== semver.brig ====
## Семантические версии (semver.org, без build-метаданных) и
## ограничения вида `^1.2`, `~1.2.3`, `>=1.0.0`, `=1.0.0`, `*`.
##
## ```brig repl
## > satisfies?(ver("1.4.2"), con("^1.2"))
## true
## > satisfies?(ver("2.0.0"), con("^1.2"))
## false
## > max_satisfying([ver("1.0.0"), ver("1.3.0"), ver("2.0.0")], con("~1.3"))
## Some(Version{ major: 1, minor: 3, patch: 0, pre: [] })
## ```
module Semver

## Версия. `pre` — идентификаторы pre-release: `1.0.0-rc.1` →
## `["rc", 1]`; числовые — `Int`, остальные — `Str`.
type Version { major: Int, minor: Int, patch: Int, pre: List<Any> }

## Ограничение на версию.
type Constraint {
    Exact(Version),
    Caret(Version),
    Tilde(Version),
    AtLeast(Version),
    Any,
}

## Ошибка разбора: что не так и исходная строка.
type ParseError { reason: Atom, input: Str }

## Разбирает версию `MAJOR.MINOR.PATCH[-PRE]`.
##
## ```brig repl
## > parse("1.2.3")
## Ok(Version{ major: 1, minor: 2, patch: 3, pre: [] })
## > parse("1.2.3-rc.1")
## Ok(Version{ major: 1, minor: 2, patch: 3, pre: ["rc", 1] })
## > parse("1.x")
## Error(ParseError{ reason: :bad_number, input: "1.x" })
## ```
pub fn parse(s) ->
    (core, pre) = split_pre(Str.trim(s))
    match Str.split(core, ".")
        [a, b, c] -> build(s, [a, b, c], pre)
        [a, b] -> build(s, [a, b, "0"], pre)
        [a] -> build(s, [a, "0", "0"], pre)
        _ -> Error(ParseError{ reason: :bad_shape, input: s })

fn split_pre(s) ->
    match Str.find(s, "-")
        Some(i) -> (Str.slice(s, 0, i), Str.slice(s, i + 1, len(s)))
        None -> (s, "")

fn build(input, parts, pre) ->
    nums = map(parts, p -> Str.to_int(p))
    match nums
        [Some(ma), Some(mi), Some(pa)] ->
            Ok(Version{ major: ma, minor: mi, patch: pa, pre: pre_ids(pre) })
        _ -> Error(ParseError{ reason: :bad_number, input: input })

fn pre_ids("") -> []
fn pre_ids(pre) -> map(Str.split(pre, "."), id -> pre_id(id, Str.to_int(id)))

fn pre_id(_id, Some(n)) -> n
fn pre_id(id, None) -> id

## Как `parse`, но бросает `(:bad_version, s)`; для литералов в коде.
pub fn ver(s) ->
    match parse(s)
        Ok(ver) -> ver
        Error(_) -> raise((:bad_version, s))

## Разбирает ограничение.
##
## ```brig repl
## > constraint("^1.2")
## Ok(Caret(Version{ major: 1, minor: 2, patch: 0, pre: [] }))
## > constraint("*")
## Ok(Any)
## ```
pub fn constraint("*") -> Ok(Any)
pub fn constraint("^" <> rest) -> Result.map(parse(rest), Caret)
pub fn constraint("~" <> rest) -> Result.map(parse(rest), Tilde)
pub fn constraint(">=" <> rest) -> Result.map(parse(rest), AtLeast)
pub fn constraint("=" <> rest) -> Result.map(parse(rest), Exact)
pub fn constraint(s) -> Result.map(parse(s), Exact)

## Как `constraint`, но бросает.
pub fn con(s) ->
    match constraint(s)
        Ok(x) -> x
        Error(_) -> raise((:bad_constraint, s))

## Порядок версий по semver: `-1`, `0`, `1`.
##
## ```brig repl
## > compare(ver("1.0.0-rc.1"), ver("1.0.0"))
## -1
## > compare(ver("1.10.0"), ver("1.9.9"))
## 1
## ```
pub fn compare(a, b) ->
    cmp_all([
        cmp(a.major, b.major),
        cmp(a.minor, b.minor),
        cmp(a.patch, b.patch),
        cmp_pre(a.pre, b.pre),
    ])

fn cmp(x, y) when x < y -> -1
fn cmp(x, y) when x > y -> 1
fn cmp(_, _) -> 0

fn cmp_all([]) -> 0
fn cmp_all([0, ..rest]) -> cmp_all(rest)
fn cmp_all([d, ..]) -> d

# Версия без pre-release старше версии с ним.
fn cmp_pre([], []) -> 0
fn cmp_pre([], _) -> 1
fn cmp_pre(_, []) -> -1
fn cmp_pre(a, b) -> cmp(a, b)

## Удовлетворяет ли версия ограничению.
pub fn satisfies?(_ver, Any) -> true
pub fn satisfies?(ver, Exact(x)) -> compare(ver, x) == 0
pub fn satisfies?(ver, AtLeast(x)) -> compare(ver, x) >= 0
pub fn satisfies?(ver, Caret(x)) ->
    compare(ver, x) >= 0 and compare(ver, caret_upper(x)) < 0
pub fn satisfies?(ver, Tilde(x)) ->
    compare(ver, x) >= 0 and compare(ver, Version{ ..x, minor: x.minor + 1, patch: 0, pre: [] }) < 0

fn caret_upper(Version{ major: 0, minor: 0, patch: p }) -> Version{ major: 0, minor: 0, patch: p + 1, pre: [] }
fn caret_upper(Version{ major: 0, minor: m }) -> Version{ major: 0, minor: m + 1, patch: 0, pre: [] }
fn caret_upper(x) -> Version{ major: x.major + 1, minor: 0, patch: 0, pre: [] }

## Наибольшая версия из списка, удовлетворяющая ограничению.
pub fn max_satisfying(versions, con) ->
    ok = filter(versions, ver -> satisfies?(ver, con))
    fold(ok, None, pick_max)

fn pick_max(None, ver) -> Some(ver)
fn pick_max(Some(best), ver) -> if compare(ver, best) > 0 then Some(ver) else Some(best)

## Следующая версия.
##
## ```brig repl
## > to_string(bump(ver("1.2.3"), :minor))
## "1.3.0"
## ```
pub fn bump(ver, :major) -> Version{ major: ver.major + 1, minor: 0, patch: 0, pre: [] }
pub fn bump(ver, :minor) -> { ..ver, minor: ver.minor + 1, patch: 0, pre: [] }
pub fn bump(ver, :patch) -> { ..ver, patch: ver.patch + 1, pre: [] }

## Строковая форма.
pub fn to_string(Version{ major: a, minor: b, patch: c, pre: [] }) -> "\(a).\(b).\(c)"
pub fn to_string(ver) ->
    ids = Str.join(map(ver.pre, to_str), ".")
    "\(ver.major).\(ver.minor).\(ver.patch)-\(ids)"

# ==== main.brig ====
## Выбор версий зависимостей: brig main.brig
module Main

import Semver

fn available() ->
    %{
        "json" => ["1.0.0", "1.2.0", "1.2.5", "2.0.0-rc.1", "2.0.0"],
        "http" => ["0.3.0", "0.3.4", "0.4.0"],
        "log" => ["1.0.0"],
    }

fn wanted() -> [("json", "^1.2"), ("http", "^0.3"), ("log", ">=2.0"), ("csv", "*"), ("xml", "~bad")]

fn resolve((name, spec)) ->
    with
        Ok(con) <- Semver.constraint(spec)
        Some(raw) <- Map.get(available(), name)
        Ok(vers) <- Result.all(map(raw, Semver.parse))
        Some(best) <- Semver.max_satisfying(vers, con)
        Ok((name, best))
    else
        Error(Semver.ParseError{ reason: r, input: i }) -> Error((name, :bad_spec, r, i))
        None -> Error((name, :no_match, spec))

fn describe(Ok((name, Semver.Version{ major: 0 } as v))) -> "\(name) \(Semver.to_string(v)) (unstable)"
fn describe(Ok((name, v))) -> "\(name) \(Semver.to_string(v))"
fn describe(Error(e)) -> "error: \(e)"

fn main() ->
    results = map(wanted(), resolve)
    _ = map(results, r -> print(describe(r)))
    next = Semver.bump(Semver.ver("1.2.3"), :major)
    print("bump:", Semver.to_string(next), next == Semver.Version{ major: 2, minor: 0, patch: 0, pre: [] })
    print(Semver.satisfies?(next, Semver.Caret(Semver.ver("2.0.0"))), Semver.compare(next, Semver.ver("2.0.0-rc.1")))
```

</details>

## Приложение B. Пробы производительности и акторов

<details>
<summary>perf1.brig, perf2.brig, a2.brig</summary>

```text
# ==== perf1.brig ====
module Main

fn build_list(0, acc) -> acc
fn build_list(n, acc) -> build_list(n - 1, [n, ..acc])

fn build_map(0, acc) -> acc
fn build_map(n, acc) -> build_map(n - 1, Map.put(acc, n, n))

fn build_vec(0, acc) -> acc
fn build_vec(n, acc) -> build_vec(n - 1, Vec.push(acc, n))

fn sum_list([], acc) -> acc
fn sum_list([h, ..t], acc) -> sum_list(t, acc + h)

fn timed(label, f) ->
    t0 = Time.monotonic_ms()
    r = f()
    print(label, Time.monotonic_ms() - t0, "ms")
    r

fn main() ->
    n = to_int(Sys.args()[0])
    xs = timed("list prepend", () -> build_list(n, []))
    _ = timed("list sum pattern", () -> sum_list(xs, 0))
    _ = timed("map put", () -> build_map(n, %{}))
    _ = timed("vec push", () -> build_vec(n, %[]))
    _ = timed("fold", () -> fold(xs, 0, (a, x) -> a + x))
    ()

# ==== perf2.brig ====
module Main
fn fib(n) when n < 2 -> n
fn fib(n) -> fib(n - 1) + fib(n - 2)
fn loop(0, acc) -> acc
fn loop(n, acc) -> loop(n - 1, acc + 1)
fn main() ->
    t0 = Time.monotonic_ms()
    print(fib(27))
    print("fib27", Time.monotonic_ms() - t0, "ms")
    t1 = Time.monotonic_ms()
    print(loop(3_000_000, 0))
    print("loop3M", Time.monotonic_ms() - t1, "ms")
    t2 = Time.monotonic_ms()
    xs = list(1 to 1_000_000)
    ys = map(xs, x -> x * 2)
    print(len(filter(ys, x -> x rem 3 == 0)))
    print("map/filter 1M", Time.monotonic_ms() - t2, "ms")

# ==== a2.brig ====
module Main
fn worker(parent) ->
    recv
        (:ping, n) ->
            send(parent, (:pong, n))
            worker(parent)
fn spawn_n(0, me) -> :ok
fn spawn_n(n, me) ->
    pid = spawn(() -> worker(me))
    Ok(()) = send(pid, (:ping, 1))
    spawn_n(n - 1, me)
fn collect(0, sum) -> sum
fn collect(n, sum) ->
    recv
        (:pong, k) -> collect(n - 1, sum + k)
    after 3000 -> (:timeout, n, sum)
fn main() ->
    n = to_int(Sys.args()[0])
    t0 = Time.monotonic_ms()
    spawn_n(n, self())
    print("spawned+sent", Time.monotonic_ms() - t0, "ms", len(Actor.list()))
    print(collect(n, 0), Time.monotonic_ms() - t0, "ms")
```

</details>
